"""
D&D 5e Character Classes

Each class is implemented as a collection of conditions that can be applied to entities.
"""

from dnd.classes.fighter import (
    create_modified_dice_roll,

    FightingStyleArchery,
    FightingStyleDefense,
    defense_ac_check,
    FightingStyleDueling,
    dueling_damage_check,
    GreatWeaponFighting,
    great_weapon_fighting_processor,
    FightingStyleProtection,
    create_protection_handler,
    protection_processor,
    FightingStyleTwoWeaponFighting,
    twf_off_hand_melee_ability_bonus,
    twf_off_hand_ranged_ability_bonus,

    SecondWind,
    SecondWindFeature,

    ActionSurging,
    ActionSurge,
    ActionSurgeFeature,

    ImprovedCritical,

    extra_attack_resource_processor,
    create_extra_attack_resource_handler,
    ExtraAttack,
    ExtraAttackFeature,
    ExtraAttacksGranted,

    Indomitable,
    create_indomitable_handler,
    indomitable_processor,

    SuperiorCritical,

    Survivor,
    create_survivor_handler,
    survivor_processor,
)

from dnd.classes.dice_processor_utils import (
    maximize_all,
    minimize_all,
    set_all_to,
    substitute_value,
    floor_results,
    ceiling_results,
    reroll_below_and_substitute,
    reroll_below_keep_best,
    reroll_ones_once,
)

from dnd.classes.fighter_factory import (
    FighterConfig,
    FightingStyleChoice,
    EquipmentPreset as FighterEquipmentPreset,
    create_fighter,
    get_proficiency_bonus,
    get_extra_attacks,
    get_action_surge_uses,
    get_indomitable_uses,
    calculate_final_ability_scores,
)

from dnd.classes.barbarian_factory import (
    BarbarianConfig,
    PrimalPathChoice,
    EquipmentPreset as BarbarianEquipmentPreset,
    create_barbarian,
    get_rage_uses,
    get_rage_damage,
    get_brutal_critical_dice,
)

from dnd.classes.rage import (
    rage_damage_check,
    rage_maintenance_processor,
    rage_armor_equip_handler,
    create_rage_maintenance_handler,
    create_rage_armor_handler,
    rage_death_processor,
    create_rage_death_handler,
    Raging,
    Rage,
    EndRage,
    RageFeature,
    Frenzied,
    FrenziedStrike,
    Frenzy,
    FrenzyFeature,
)

from dnd.classes.paladin import (
    create_divine_smite_processor,
    create_divine_smite_handler,
    register_divine_smite,
    MAX_SMITE_DICE,
)

from dnd.classes.sorcerer_factory import (
    SorcererConfig,
    SorcererOriginChoice,
    SorcererEquipmentPreset,
    create_sorcerer as create_sorcerer_class,
    get_sorcery_points,
    get_sorcerer_spell_slots,
    get_metamagic_count,
)

from dnd.classes.sorcerer import (
    DraconicResilience,
    ElementalAffinity,
    SorceryPointsFeature,
    MetamagicActive,
    QuickenedSpell,
    TwinnedSpell,
    DistantSpell,
    METAMAGIC_ACTIONS,
    ConvertSlotToSP,
    ConvertSPToSlot,
)

__all__ = [
    "create_modified_dice_roll",
    "maximize_all",
    "minimize_all",
    "set_all_to",
    "substitute_value",
    "floor_results",
    "ceiling_results",
    "reroll_below_and_substitute",
    "reroll_below_keep_best",
    "reroll_ones_once",
    "FightingStyleArchery",
    "FightingStyleDefense",
    "defense_ac_check",
    "FightingStyleDueling",
    "dueling_damage_check",
    "GreatWeaponFighting",
    "great_weapon_fighting_processor",
    "FightingStyleProtection",
    "create_protection_handler",
    "protection_processor",
    "FightingStyleTwoWeaponFighting",
    "twf_off_hand_melee_ability_bonus",
    "twf_off_hand_ranged_ability_bonus",
    "SecondWind",
    "SecondWindFeature",
    "ActionSurging",
    "ActionSurge",
    "ActionSurgeFeature",
    "ImprovedCritical",
    "extra_attack_resource_processor",
    "create_extra_attack_resource_handler",
    "ExtraAttack",
    "ExtraAttackFeature",
    "ExtraAttacksGranted",
    "Indomitable",
    "create_indomitable_handler",
    "indomitable_processor",
    "SuperiorCritical",
    "Survivor",
    "create_survivor_handler",
    "survivor_processor",
    "FighterConfig",
    "FightingStyleChoice",
    "FighterEquipmentPreset",
    "create_fighter",
    "get_proficiency_bonus",
    "get_extra_attacks",
    "get_action_surge_uses",
    "get_indomitable_uses",
    "calculate_final_ability_scores",
    "BarbarianConfig",
    "PrimalPathChoice",
    "BarbarianEquipmentPreset",
    "create_barbarian",
    "get_rage_uses",
    "get_rage_damage",
    "get_brutal_critical_dice",
    "rage_damage_check",
    "rage_maintenance_processor",
    "rage_armor_equip_handler",
    "create_rage_maintenance_handler",
    "create_rage_armor_handler",
    "rage_death_processor",
    "create_rage_death_handler",
    "Raging",
    "Rage",
    "EndRage",
    "RageFeature",
    "Frenzied",
    "FrenziedStrike",
    "Frenzy",
    "FrenzyFeature",
    "create_divine_smite_processor",
    "create_divine_smite_handler",
    "register_divine_smite",
    "MAX_SMITE_DICE",
    "SorcererConfig",
    "SorcererOriginChoice",
    "SorcererEquipmentPreset",
    "create_sorcerer_class",
    "get_sorcery_points",
    "get_sorcerer_spell_slots",
    "get_metamagic_count",
    "DraconicResilience",
    "ElementalAffinity",
    "SorceryPointsFeature",
    "MetamagicActive",
    "QuickenedSpell",
    "TwinnedSpell",
    "DistantSpell",
    "METAMAGIC_ACTIONS",
    "ConvertSlotToSP",
    "ConvertSPToSlot",
]
