"""Item factory exports and lookup tables."""

from dnd.items.weapons import (
    create_club,
    create_dagger,
    create_handaxe,
    create_javelin,
    create_mace,
    create_quarterstaff,
    create_spear,
    create_light_crossbow,
    create_shortbow,
    create_battleaxe,
    create_greataxe,
    create_greatsword,
    create_longsword,
    create_rapier,
    create_scimitar,
    create_shortsword,
    create_warhammer,
    create_longbow,
    create_heavy_crossbow,
    create_arcane_staff,
)

from dnd.items.armors import (
    create_padded_armor,
    create_leather_armor,
    create_studded_leather,
    create_hide_armor,
    create_chain_shirt,
    create_scale_mail,
    create_breastplate,
    create_half_plate,
    create_ring_mail,
    create_chain_mail,
    create_splint_armor,
    create_plate_armor,
    create_common_clothes,
    create_travelers_clothes,
    create_costume,
    create_robes,
    create_cloth_shoes,
    create_sandals,
    create_leather_shoes,
    create_leather_boots,
    create_armored_boots,
    create_iron_helmet,
    create_wizard_hat,
    create_crown,
    create_shield,
    create_wooden_shield,
)

from dnd.items.environment import (
    DirectionalDoor,
    DirectionalWall,
    OpenDirectionalDoorAction,
    CloseDirectionalDoorAction,
)

from dnd.items.test_items import (
    HealingPotion,
    create_healing_potion,
)

WEAPONS = {
    "club": create_club,
    "dagger": create_dagger,
    "handaxe": create_handaxe,
    "javelin": create_javelin,
    "mace": create_mace,
    "quarterstaff": create_quarterstaff,
    "spear": create_spear,
    "light_crossbow": create_light_crossbow,
    "shortbow": create_shortbow,
    "battleaxe": create_battleaxe,
    "greataxe": create_greataxe,
    "greatsword": create_greatsword,
    "longsword": create_longsword,
    "rapier": create_rapier,
    "scimitar": create_scimitar,
    "shortsword": create_shortsword,
    "warhammer": create_warhammer,
    "longbow": create_longbow,
    "heavy_crossbow": create_heavy_crossbow,
}

ARMORS = {
    "padded": create_padded_armor,
    "leather": create_leather_armor,
    "studded_leather": create_studded_leather,
    "hide": create_hide_armor,
    "chain_shirt": create_chain_shirt,
    "scale_mail": create_scale_mail,
    "breastplate": create_breastplate,
    "half_plate": create_half_plate,
    "ring_mail": create_ring_mail,
    "chain_mail": create_chain_mail,
    "splint": create_splint_armor,
    "plate": create_plate_armor,
    "common_clothes": create_common_clothes,
    "travelers_clothes": create_travelers_clothes,
    "costume": create_costume,
    "robes": create_robes,
    "sandals": create_sandals,
    "cloth_shoes": create_cloth_shoes,
    "leather_shoes": create_leather_shoes,
    "leather_boots": create_leather_boots,
    "armored_boots": create_armored_boots,
    "iron_helmet": create_iron_helmet,
    "wizard_hat": create_wizard_hat,
    "crown": create_crown,
}

SHIELDS = {
    "shield": create_shield,
    "wooden_shield": create_wooden_shield,
}

__all__ = [
    "create_club",
    "create_dagger",
    "create_handaxe",
    "create_javelin",
    "create_mace",
    "create_quarterstaff",
    "create_spear",
    "create_light_crossbow",
    "create_shortbow",
    "create_battleaxe",
    "create_greataxe",
    "create_greatsword",
    "create_longsword",
    "create_rapier",
    "create_scimitar",
    "create_shortsword",
    "create_warhammer",
    "create_longbow",
    "create_heavy_crossbow",
    "create_arcane_staff",
    "create_padded_armor",
    "create_leather_armor",
    "create_studded_leather",
    "create_hide_armor",
    "create_chain_shirt",
    "create_scale_mail",
    "create_breastplate",
    "create_half_plate",
    "create_ring_mail",
    "create_chain_mail",
    "create_splint_armor",
    "create_plate_armor",
    "create_common_clothes",
    "create_travelers_clothes",
    "create_costume",
    "create_robes",
    "create_cloth_shoes",
    "create_sandals",
    "create_leather_shoes",
    "create_leather_boots",
    "create_armored_boots",
    "create_iron_helmet",
    "create_wizard_hat",
    "create_crown",
    "create_shield",
    "create_wooden_shield",
    "DirectionalDoor",
    "DirectionalWall",
    "OpenDirectionalDoorAction",
    "CloseDirectionalDoorAction",
    "HealingPotion",
    "create_healing_potion",
    "WEAPONS",
    "ARMORS",
    "SHIELDS",
]
