"""Item factory exports and lookup tables."""

from dnd.items.weapons import (
    NEURODRAGON_WEAPON_DECLARATIONS,
    NEURODRAGON_WEAPON_RECIPES_BY_LEGACY_ID,
    SRD_WEAPON_DECLARATIONS,
    SRD_WEAPON_RECIPES_BY_LEGACY_ID,
)

from dnd.items.armors import (
    NEURODRAGON_ARMOR_DECLARATIONS,
    NEURODRAGON_ARMOR_RECIPES_BY_LEGACY_ID,
    SRD_ARMOR_DECLARATIONS,
    SRD_ARMOR_RECIPES_BY_LEGACY_ID,
)

from dnd.items.consumables import (
    CONCENTRATION_FIRE_WEAPON_COAT_RECIPE,
    FIRE_WEAPON_COAT_RECIPE,
    GREATER_INVISIBILITY_POTION_RECIPE,
    HASTE_POTION_RECIPE,
    HEALING_POTION_RECIPE,
    LIGHTNING_WEAPON_COAT_RECIPE,
    NEURODRAGON_CONSUMABLE_DECLARATIONS,
    NEURODRAGON_CONSUMABLE_RECIPES_BY_LEGACY_ID,
    TIMED_FIRE_WEAPON_COAT_RECIPE,
    healing_potion_recipe,
    timed_fire_weapon_coat_recipe,
)

from dnd.items.spell_items import (
    ACID_FLASK_RECIPE,
    FIREBALL_SCROLL_RECIPE,
    FIRE_BOLT_SCROLL_RECIPE,
    HOLD_PERSON_SCROLL_RECIPE,
    INVISIBILITY_SCROLL_RECIPE,
    MAGE_ARMOR_SCROLL_RECIPE,
    MAGIC_MISSILE_SCROLL_RECIPE,
    NEURODRAGON_SPELL_ITEM_DECLARATIONS,
    NEURODRAGON_SPELL_ITEM_RECIPES_BY_LEGACY_ID,
    SPELL_ITEM_DEPENDENCY_DECLARATIONS,
    SPIKE_GROWTH_SCROLL_RECIPE,
    WAND_OF_FIRE_RECIPE,
    WAND_OF_MAGIC_MISSILES_RECIPE,
    fire_bolt_scroll_recipe,
    fireball_scroll_recipe,
    hold_person_scroll_recipe,
    invisibility_scroll_recipe,
    mage_armor_scroll_recipe,
    magic_missile_scroll_recipe,
    spike_growth_scroll_recipe,
    wand_of_fire_recipe,
    wand_of_magic_missiles_recipe,
)

from dnd.items.environment import (
    DirectionalDoor,
    DirectionalWall,
    OpenDirectionalDoorAction,
    CloseDirectionalDoorAction,
)
from dnd.items.torches import (
    NEURODRAGON_TORCH_DECLARATIONS,
    TORCH_DECLARATION,
    TORCH_RECIPE,
    Torch,
)

__all__ = [
    "NEURODRAGON_WEAPON_DECLARATIONS",
    "NEURODRAGON_WEAPON_RECIPES_BY_LEGACY_ID",
    "SRD_WEAPON_DECLARATIONS",
    "SRD_WEAPON_RECIPES_BY_LEGACY_ID",
    "NEURODRAGON_ARMOR_DECLARATIONS",
    "NEURODRAGON_ARMOR_RECIPES_BY_LEGACY_ID",
    "SRD_ARMOR_DECLARATIONS",
    "SRD_ARMOR_RECIPES_BY_LEGACY_ID",
    "CONCENTRATION_FIRE_WEAPON_COAT_RECIPE",
    "FIRE_WEAPON_COAT_RECIPE",
    "GREATER_INVISIBILITY_POTION_RECIPE",
    "HASTE_POTION_RECIPE",
    "HEALING_POTION_RECIPE",
    "LIGHTNING_WEAPON_COAT_RECIPE",
    "NEURODRAGON_CONSUMABLE_DECLARATIONS",
    "NEURODRAGON_CONSUMABLE_RECIPES_BY_LEGACY_ID",
    "TIMED_FIRE_WEAPON_COAT_RECIPE",
    "healing_potion_recipe",
    "timed_fire_weapon_coat_recipe",
    "ACID_FLASK_RECIPE",
    "FIREBALL_SCROLL_RECIPE",
    "FIRE_BOLT_SCROLL_RECIPE",
    "HOLD_PERSON_SCROLL_RECIPE",
    "INVISIBILITY_SCROLL_RECIPE",
    "MAGE_ARMOR_SCROLL_RECIPE",
    "MAGIC_MISSILE_SCROLL_RECIPE",
    "NEURODRAGON_SPELL_ITEM_DECLARATIONS",
    "NEURODRAGON_SPELL_ITEM_RECIPES_BY_LEGACY_ID",
    "SPELL_ITEM_DEPENDENCY_DECLARATIONS",
    "SPIKE_GROWTH_SCROLL_RECIPE",
    "WAND_OF_FIRE_RECIPE",
    "WAND_OF_MAGIC_MISSILES_RECIPE",
    "fire_bolt_scroll_recipe",
    "fireball_scroll_recipe",
    "hold_person_scroll_recipe",
    "invisibility_scroll_recipe",
    "mage_armor_scroll_recipe",
    "magic_missile_scroll_recipe",
    "spike_growth_scroll_recipe",
    "wand_of_fire_recipe",
    "wand_of_magic_missiles_recipe",
    "DirectionalDoor",
    "DirectionalWall",
    "OpenDirectionalDoorAction",
    "CloseDirectionalDoorAction",
    "NEURODRAGON_TORCH_DECLARATIONS",
    "TORCH_DECLARATION",
    "TORCH_RECIPE",
    "Torch",
]
