"""Exact declaration and preset inventory for trusted built-in content."""

from __future__ import annotations

from types import MappingProxyType

from dnd.actions import (
    CORE_STANDARD_ACTION_DECLARATIONS,
    CORE_STANDARD_ACTION_DECLARATIONS_BY_CLASS,
)
from dnd.conditions import (
    CORE_STANDARD_CONDITION_DECLARATIONS,
    CORE_STANDARD_CONDITION_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.action_definitions import (
    ACTION_BEHAVIOR_DECLARATIONS,
    ACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.condition_definitions import (
    CONDITION_BEHAVIOR_DECLARATIONS,
    CONDITION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.condition_effect_population import (
    populate_builtin_condition_effects,
)
from dnd.content_system.reaction_definitions import (
    REACTION_BEHAVIOR_DECLARATIONS,
    REACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.core.content.recipe_presets import ContentRecipePreset
from dnd.core.content.registration import (
    ContentDeclaration,
    ContentDeclarationMode,
)
from dnd.content.characters.class_definitions import (
    CHARACTER_RETIRED_DECLARATION_IDS,
)
from dnd.items.spell_items import (
    ACID_FLASK_SPELL_DECLARATION,
    SPELL_ITEM_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.monsters.bestiary_content import BESTIARY_CREATURE_DECLARATIONS
from dnd.monsters.multiattack_definitions import (
    SRD_MULTIATTACK_CONFIGURATION_DECLARATIONS,
)
from dnd.monsters.configured_srd_creatures import (
    CONFIGURED_SRD_CREATURE_DECLARATIONS,
)
from dnd.monsters.srd_roster import SRD_CREATURE_DECLARATIONS
from dnd.spells.abjuration import (
    ABJURATION_REACTION_DECLARATIONS_BY_CLASS,
    COUNTERSPELL_REACTION_DECLARATION,
    SHIELD_REACTION_DECLARATION,
)
from dnd.spells.catalog_content import (
    SPELL_CONTENT_DECLARATIONS,
    SPELL_CONTENT_DECLARATIONS_BY_CLASS,
)
from dnd.spells.reaction_spell_content import (
    LEARNED_REACTION_SPELL_DECLARATIONS,
    LEARNED_REACTION_SPELL_DECLARATIONS_BY_CLASS,
)
from dnd.spells.infernal import (
    HELLISH_REBUKE_REACTION_DECLARATION,
    HELLISH_REBUKE_SPELL_DECLARATION,
    INFERNAL_BEHAVIOR_DECLARATIONS_BY_CLASS,
    THAUMATURGY_SPELL_DECLARATION,
)


_ALL_BUILT_IN_DECLARATIONS: tuple[
    ContentDeclaration,
    ...,
] = (
    *CORE_STANDARD_ACTION_DECLARATIONS,
    *CORE_STANDARD_CONDITION_DECLARATIONS,
    *ACTION_BEHAVIOR_DECLARATIONS,
    *CONDITION_BEHAVIOR_DECLARATIONS,
    *REACTION_BEHAVIOR_DECLARATIONS,
    COUNTERSPELL_REACTION_DECLARATION,
    SHIELD_REACTION_DECLARATION,
    *LEARNED_REACTION_SPELL_DECLARATIONS,
    HELLISH_REBUKE_REACTION_DECLARATION,
    HELLISH_REBUKE_SPELL_DECLARATION,
    THAUMATURGY_SPELL_DECLARATION,
    *CONFIGURED_SRD_CREATURE_DECLARATIONS,
    *BESTIARY_CREATURE_DECLARATIONS,
    ACID_FLASK_SPELL_DECLARATION,
    *SPELL_CONTENT_DECLARATIONS,
    *SRD_MULTIATTACK_CONFIGURATION_DECLARATIONS,
    *SRD_CREATURE_DECLARATIONS,
)
_UNPOPULATED_BUILT_IN_DECLARATION_INVENTORY = tuple(
    declaration
    for declaration in _ALL_BUILT_IN_DECLARATIONS
    if declaration.ref.content_id not in CHARACTER_RETIRED_DECLARATION_IDS
)
BUILT_IN_DECLARATION_INVENTORY = populate_builtin_condition_effects(
    _UNPOPULATED_BUILT_IN_DECLARATION_INVENTORY,
)
_ALL_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS = {
    **ACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **CONDITION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **SPELL_CONTENT_DECLARATIONS_BY_CLASS,
    **CORE_STANDARD_ACTION_DECLARATIONS_BY_CLASS,
    **CORE_STANDARD_CONDITION_DECLARATIONS_BY_CLASS,
    **REACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **ABJURATION_REACTION_DECLARATIONS_BY_CLASS,
    **LEARNED_REACTION_SPELL_DECLARATIONS_BY_CLASS,
    **INFERNAL_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **SPELL_ITEM_BEHAVIOR_DECLARATIONS_BY_CLASS,
}
_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS = {
    behavior_class: declaration
    for behavior_class, declaration
    in _ALL_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS.items()
    if declaration.ref.content_id not in CHARACTER_RETIRED_DECLARATION_IDS
}
_BUILT_IN_CLASS_BEHAVIOR_IDS = {
    declaration.ref.content_id
    for declaration in _BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS.values()
}
if (
    len(_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS) != 311
    or len(_BUILT_IN_CLASS_BEHAVIOR_IDS) != 311
):
    raise ValueError("Built-in behavior class inventory is not one-to-one")
BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS = MappingProxyType(
    _BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS = frozenset()
_BUILT_IN_BEHAVIOR_IDS = {
    declaration.ref.content_id
    for declaration in BUILT_IN_DECLARATION_INVENTORY
    if declaration.mode is ContentDeclarationMode.BEHAVIOR_IDENTITY
}
if (
    len(_BUILT_IN_BEHAVIOR_IDS) != 311
    or _BUILT_IN_CLASS_BEHAVIOR_IDS & BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS
    or (
        _BUILT_IN_CLASS_BEHAVIOR_IDS | BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS
        != _BUILT_IN_BEHAVIOR_IDS
    )
):
    raise ValueError("Built-in behavior admission partitions are incomplete")
BUILT_IN_RECIPE_PRESET_INVENTORY: tuple[ContentRecipePreset, ...] = (
)


__all__ = [
    "BUILT_IN_DECLARATION_INVENTORY",
    "BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS",
    "BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS",
    "BUILT_IN_RECIPE_PRESET_INVENTORY",
]
