"""Exact declaration and preset inventory for trusted built-in content."""

from __future__ import annotations

from types import MappingProxyType

from dnd.actions import (
    CORE_STANDARD_ACTION_DECLARATIONS,
    CORE_STANDARD_ACTION_DECLARATIONS_BY_CLASS,
)
from dnd.classes.barbarian_progression_definitions import (
    BARBARIAN_PROGRESSION_DECLARATIONS,
)
from dnd.classes.content_factories import PLAYER_CLASS_CREATURE_DECLARATIONS
from dnd.classes.progression_definitions import (
    FIGHTER_PROGRESSION_DECLARATIONS,
)
from dnd.classes.sorcerer_progression_definitions import (
    SORCERER_PROGRESSION_DECLARATIONS,
)
from dnd.classes.sorcerer_structural_feature_definitions import (
    SORCERER_STRUCTURAL_FEATURE_DECLARATIONS,
    SORCERER_STRUCTURAL_FEATURE_DECLARATIONS_BY_CLASS,
)
from dnd.classes.structural_feature_definitions import (
    STRUCTURAL_CLASS_FEATURE_DECLARATIONS,
    STRUCTURAL_CLASS_FEATURE_DECLARATIONS_BY_CLASS,
)
from dnd.conditions import (
    CORE_STANDARD_CONDITION_DECLARATIONS,
    CORE_STANDARD_CONDITION_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.action_definitions import (
    ACTION_BEHAVIOR_DECLARATIONS,
    ACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.character_origin_definitions import (
    NEURODRAGON_CHARACTER_ORIGIN_DECLARATIONS,
    SRD_CHARACTER_ORIGIN_DECLARATIONS,
)
from dnd.content_system.origin_feature_definitions import (
    SRD_PASSIVE_ORIGIN_FEATURE_DECLARATIONS,
)
from dnd.content_system.condition_definitions import (
    CONDITION_BEHAVIOR_DECLARATIONS,
    CONDITION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.condition_effect_population import (
    populate_builtin_condition_effects,
)
from dnd.content_system.dragonborn_origin_definitions import (
    DRAGONBORN_ANCESTRY_DECLARATIONS,
)
from dnd.content_system.reaction_definitions import (
    REACTION_BEHAVIOR_DECLARATIONS,
    REACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.content_system.starting_equipment_definitions import (
    STARTING_EQUIPMENT_PACKAGE_DECLARATIONS,
)
from dnd.content_system.starting_apparel_definitions import (
    STARTING_APPAREL_PACKAGE_DECLARATIONS,
)
from dnd.content_system.acolyte_starting_holdings import (
    ACOLYTE_STARTING_HOLDINGS_DECLARATION,
)
from dnd.core.content.recipe_presets import ContentRecipePreset
from dnd.core.content.registration import (
    ContentDeclaration,
    ContentDeclarationMode,
)
from dnd.items.spell_items import (
    ACID_FLASK_SPELL_DECLARATION,
    SPELL_ITEM_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
from dnd.monsters.bestiary_content import BESTIARY_CREATURE_DECLARATIONS
from dnd.monsters.multiattack_definitions import (
    SRD_MULTIATTACK_CONFIGURATION_DECLARATIONS,
)
from dnd.monsters.configured_srd_creatures import (
    CONFIGURED_SRD_CREATURE_DECLARATIONS,
)
from dnd.monsters.srd_roster import SRD_CREATURE_DECLARATIONS
from dnd.origins.dragonborn import (
    DRAGONBORN_BEHAVIOR_DECLARATIONS_BY_CLASS,
    DRAGONBORN_BREATH_WEAPON_DECLARATION,
)
from dnd.origins.halfling import HALFLING_LUCKY_DECLARATION
from dnd.origins.half_orc import (
    HALF_ORC_RELENTLESS_ENDURANCE_DECLARATION,
)
from dnd.premade_characters import NEURODRAGON_PREMADE_CREATURE_DECLARATIONS
from dnd.player_character_body import PLAYER_CHARACTER_BODY_DECLARATION
from dnd.spells.abjuration import (
    ABJURATION_REACTION_DECLARATIONS_BY_CLASS,
    COUNTERSPELL_REACTION_DECLARATION,
    SHIELD_REACTION_DECLARATION,
)
from dnd.spells.catalog_content import (
    SPELL_CONTENT_DECLARATIONS,
    SPELL_CONTENT_DECLARATIONS_BY_CLASS,
)
from dnd.spells.reaction_spell_content import (
    LEARNED_REACTION_SPELL_DECLARATIONS,
    LEARNED_REACTION_SPELL_DECLARATIONS_BY_CLASS,
)
from dnd.spells.infernal import (
    HELLISH_REBUKE_REACTION_DECLARATION,
    HELLISH_REBUKE_SPELL_DECLARATION,
    INFERNAL_BEHAVIOR_DECLARATIONS_BY_CLASS,
    THAUMATURGY_SPELL_DECLARATION,
)


_UNPOPULATED_BUILT_IN_DECLARATION_INVENTORY: tuple[
    ContentDeclaration,
    ...,
] = (
    *CORE_STANDARD_ACTION_DECLARATIONS,
    *CORE_STANDARD_CONDITION_DECLARATIONS,
    *ACTION_BEHAVIOR_DECLARATIONS,
    *CONDITION_BEHAVIOR_DECLARATIONS,
    *REACTION_BEHAVIOR_DECLARATIONS,
    *STRUCTURAL_CLASS_FEATURE_DECLARATIONS,
    *SORCERER_STRUCTURAL_FEATURE_DECLARATIONS,
    *SRD_CHARACTER_ORIGIN_DECLARATIONS,
    *NEURODRAGON_CHARACTER_ORIGIN_DECLARATIONS,
    *SRD_PASSIVE_ORIGIN_FEATURE_DECLARATIONS,
    *DRAGONBORN_ANCESTRY_DECLARATIONS,
    DRAGONBORN_BREATH_WEAPON_DECLARATION,
    HALF_ORC_RELENTLESS_ENDURANCE_DECLARATION,
    HALFLING_LUCKY_DECLARATION,
    *STARTING_EQUIPMENT_PACKAGE_DECLARATIONS,
    *STARTING_APPAREL_PACKAGE_DECLARATIONS,
    ACOLYTE_STARTING_HOLDINGS_DECLARATION,
    *BARBARIAN_PROGRESSION_DECLARATIONS,
    *FIGHTER_PROGRESSION_DECLARATIONS,
    *SORCERER_PROGRESSION_DECLARATIONS,
    COUNTERSPELL_REACTION_DECLARATION,
    SHIELD_REACTION_DECLARATION,
    *LEARNED_REACTION_SPELL_DECLARATIONS,
    HELLISH_REBUKE_REACTION_DECLARATION,
    HELLISH_REBUKE_SPELL_DECLARATION,
    THAUMATURGY_SPELL_DECLARATION,
    *CONFIGURED_SRD_CREATURE_DECLARATIONS,
    *BESTIARY_CREATURE_DECLARATIONS,
    *NEURODRAGON_PREMADE_CREATURE_DECLARATIONS,
    PLAYER_CHARACTER_BODY_DECLARATION,
    *PLAYER_CLASS_CREATURE_DECLARATIONS,
    ACID_FLASK_SPELL_DECLARATION,
    *SPELL_CONTENT_DECLARATIONS,
    *SRD_MULTIATTACK_CONFIGURATION_DECLARATIONS,
    *SRD_CREATURE_DECLARATIONS,
)
BUILT_IN_DECLARATION_INVENTORY = populate_builtin_condition_effects(
    _UNPOPULATED_BUILT_IN_DECLARATION_INVENTORY,
)
_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS = {
    **ACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **CONDITION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **SPELL_CONTENT_DECLARATIONS_BY_CLASS,
    **CORE_STANDARD_ACTION_DECLARATIONS_BY_CLASS,
    **CORE_STANDARD_CONDITION_DECLARATIONS_BY_CLASS,
    **STRUCTURAL_CLASS_FEATURE_DECLARATIONS_BY_CLASS,
    **SORCERER_STRUCTURAL_FEATURE_DECLARATIONS_BY_CLASS,
    **REACTION_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **DRAGONBORN_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **ABJURATION_REACTION_DECLARATIONS_BY_CLASS,
    **LEARNED_REACTION_SPELL_DECLARATIONS_BY_CLASS,
    **INFERNAL_BEHAVIOR_DECLARATIONS_BY_CLASS,
    **SPELL_ITEM_BEHAVIOR_DECLARATIONS_BY_CLASS,
}
_BUILT_IN_CLASS_BEHAVIOR_IDS = {
    declaration.ref.content_id
    for declaration in _BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS.values()
}
if (
    len(_BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS) != 393
    or len(_BUILT_IN_CLASS_BEHAVIOR_IDS) != 393
):
    raise ValueError("Built-in behavior class inventory is not one-to-one")
BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS = MappingProxyType(
    _BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS,
)
BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS = frozenset({
    HALF_ORC_RELENTLESS_ENDURANCE_DECLARATION.ref.content_id,
    HALFLING_LUCKY_DECLARATION.ref.content_id,
})
_BUILT_IN_BEHAVIOR_IDS = {
    declaration.ref.content_id
    for declaration in BUILT_IN_DECLARATION_INVENTORY
    if declaration.mode is ContentDeclarationMode.BEHAVIOR_IDENTITY
}
if (
    len(_BUILT_IN_BEHAVIOR_IDS) != 395
    or _BUILT_IN_CLASS_BEHAVIOR_IDS & BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS
    or (
        _BUILT_IN_CLASS_BEHAVIOR_IDS | BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS
        != _BUILT_IN_BEHAVIOR_IDS
    )
):
    raise ValueError("Built-in behavior admission partitions are incomplete")
BUILT_IN_RECIPE_PRESET_INVENTORY: tuple[ContentRecipePreset, ...] = (
)


__all__ = [
    "BUILT_IN_DECLARATION_INVENTORY",
    "BUILT_IN_BEHAVIOR_DECLARATIONS_BY_CLASS",
    "BUILT_IN_PROVIDER_ONLY_BEHAVIOR_IDS",
    "BUILT_IN_RECIPE_PRESET_INVENTORY",
]
