"""Spell catalog exports organized by school and spell level."""
from dnd.spells.base import SpellAction, SpellEvent
from dnd.spells.evocation import (
    FireBolt, SacredFlame, MagicMissile, Fireball,
    BurningHands, LightningBolt, Thunderwave, Shatter, Sunburst,
    ConeOfCold, CircleOfDeath, RayOfFrost, ScorchingRay,
    ShockingGrasp, GuidingBolt, GuidingBoltMarked, EldritchBlast,
    GustOfWind, IceStorm, Sunbeam, ChainLightning, PrismaticSpray,
    TrueStrike, register_true_strike,
    FlameStrike, Light, LightEffect, ContinualFlame, ContinualFlameObject,
    CureWounds, HealingWord, PrayerOfHealing, MassHealingWord,
    MassCureWounds, HealSpell, MassHeal,
    DivineWord, DivineWordEffect,
)
from dnd.spells.abjuration import MageArmor, ProtectionFromEnergy, Stoneskin, register_shield_reaction, register_counterspell_reaction, GlobeOfInvulnerability, Banishment, LesserRestoration, GreaterRestoration, RemoveCurse, ProtectionFromPoison, DeathWard, FreedomOfMovement, Resistance, ResistanceEffect, ShieldOfFaith, ShieldOfFaithEffect, Aid, AidEffect, Sanctuary, SanctuaryEffect, BeaconOfHope, BeaconOfHopeEffect, AntimagicField
from dnd.spells.enchantment import HoldPerson, HoldMonster, PowerWordKill, PowerWordStun, PowerWordStunEffect, CharmPerson, Sleep, Bane, BaneEffect, Bless, BlessEffect, Command, CommandGrovelEffect, CommandHaltEffect, CommandFleeEffect
from dnd.spells.conjuration import CallLightning, CallLightningStrike, PoisonSpray, AcidSplash, MistyStep, Grease, Web, Cloudkill, SpiritGuardians, FogCloud, Darkness, Daylight, InsectPlague, IncendiaryCloud, StinkingCloud, SleetStorm, DimensionDoor, GuardianOfFaith, GuardianOfFaithObject, GuardianWarded, HeroesFeast, HeroesFeastObject, HeroesFeastBuff, EatFromFeast
from dnd.spells.necromancy import Blight, BlindnessDeafness, FalseLife, ChillTouch, NoHealing, NecroticBless, Eyebite, FingerOfDeath, InflictWounds, Harm, BestowCurse, AbilityCurseEffect, AttackCurseEffect, InactionCurseEffect, DamageCurseEffect
from dnd.spells.illusion import Blur, Fear, HypnoticPattern, ColorSpray, Invisibility, GreaterInvisibility, MirrorImage, Silence, SilenceZone
from dnd.spells.transmutation import SpikeGrowth, Slow, Haste, DarkvisionSpell, Disintegrate, JumpSpell, ExpeditiousRetreat, EnhanceAbility, EnlargeReduce, Telekinesis, Regenerate, RegeneratingEffect
from dnd.spells.divination import SeeInvisibility, TrueSeeing, Guidance, GuidanceEffect

CANTRIPS = {
    "Fire Bolt": FireBolt,
    "Sacred Flame": SacredFlame,
    "Poison Spray": PoisonSpray,
    "Ray of Frost": RayOfFrost,
    "Acid Splash": AcidSplash,
    "Chill Touch": ChillTouch,
    "Shocking Grasp": ShockingGrasp,
    "Eldritch Blast": EldritchBlast,
    "True Strike": TrueStrike,
    "Guidance": Guidance,
    "Light": Light,
    "Resistance": Resistance,
}

LEVEL_1_SPELLS = {
    "Magic Missile": MagicMissile,
    "Mage Armor": MageArmor,
    "Burning Hands": BurningHands,
    "Thunderwave": Thunderwave,
    "False Life": FalseLife,
    "Charm Person": CharmPerson,
    "Sleep": Sleep,
    "Color Spray": ColorSpray,
    "Guiding Bolt": GuidingBolt,
    "Grease": Grease,
    "Fog Cloud": FogCloud,
    "Bane": Bane,
    "Bless": Bless,
    "Jump": JumpSpell,
    "Expeditious Retreat": ExpeditiousRetreat,
    "Command": Command,
    "Cure Wounds": CureWounds,
    "Healing Word": HealingWord,
    "Inflict Wounds": InflictWounds,
    "Shield of Faith": ShieldOfFaith,
    "Sanctuary": Sanctuary,
}

LEVEL_2_SPELLS = {
    "Hold Person": HoldPerson,
    "Shatter": Shatter,
    "Scorching Ray": ScorchingRay,
    "Blur": Blur,
    "Misty Step": MistyStep,
    "Blindness/Deafness": BlindnessDeafness,
    "Spike Growth": SpikeGrowth,
    "Web": Web,
    "Invisibility": Invisibility,
    "Darkness": Darkness,
    "Mirror Image": MirrorImage,
    "Necrotic Bless": NecroticBless,
    "Darkvision": DarkvisionSpell,
    "See Invisibility": SeeInvisibility,
    "Gust of Wind": GustOfWind,
    "Enhance Ability": EnhanceAbility,
    "Enlarge/Reduce": EnlargeReduce,
    "Silence": Silence,
    "Continual Flame": ContinualFlame,
    "Prayer of Healing": PrayerOfHealing,
    "Lesser Restoration": LesserRestoration,
    "Protection from Poison": ProtectionFromPoison,
    "Aid": Aid,
}

LEVEL_3_SPELLS = {
    "Call Lightning": CallLightning,
    "Fireball": Fireball,
    "Lightning Bolt": LightningBolt,
    "Protection from Energy": ProtectionFromEnergy,
    "Fear": Fear,
    "Hypnotic Pattern": HypnoticPattern,
    "Spirit Guardians": SpiritGuardians,
    "Daylight": Daylight,
    "Slow": Slow,
    "Haste": Haste,
    "Stinking Cloud": StinkingCloud,
    "Sleet Storm": SleetStorm,
    "Mass Healing Word": MassHealingWord,
    "Beacon of Hope": BeaconOfHope,
    "Remove Curse": RemoveCurse,
    "Bestow Curse": BestowCurse,
}

LEVEL_4_SPELLS = {
    "Blight": Blight,
    "Stoneskin": Stoneskin,
    "Greater Invisibility": GreaterInvisibility,
    "Ice Storm": IceStorm,
    "Dimension Door": DimensionDoor,
    "Banishment": Banishment,
    "Guardian of Faith": GuardianOfFaith,
    "Death Ward": DeathWard,
    "Freedom of Movement": FreedomOfMovement,
}

LEVEL_5_SPELLS = {
    "Hold Monster": HoldMonster,
    "Cone of Cold": ConeOfCold,
    "Cloudkill": Cloudkill,
    "Insect Plague": InsectPlague,
    "Telekinesis": Telekinesis,
    "Flame Strike": FlameStrike,
    "Mass Cure Wounds": MassCureWounds,
    "Greater Restoration": GreaterRestoration,
}

LEVEL_6_SPELLS = {
    "Circle of Death": CircleOfDeath,
    "Disintegrate": Disintegrate,
    "True Seeing": TrueSeeing,
    "Sunbeam": Sunbeam,
    "Chain Lightning": ChainLightning,
    "Eyebite": Eyebite,
    "Globe of Invulnerability": GlobeOfInvulnerability,
    "Heal": HealSpell,
    "Harm": Harm,
    "Heroes' Feast": HeroesFeast,
}

LEVEL_7_SPELLS = {
    "Prismatic Spray": PrismaticSpray,
    "Finger of Death": FingerOfDeath,
    "Regenerate": Regenerate,
    "Divine Word": DivineWord,
}

LEVEL_8_SPELLS = {
    "Sunburst": Sunburst,
    "Power Word Stun": PowerWordStun,
    "Incendiary Cloud": IncendiaryCloud,
    "Antimagic Field": AntimagicField,
}

LEVEL_9_SPELLS = {
    "Power Word Kill": PowerWordKill,
    "Mass Heal": MassHeal,
}

ALL_SPELLS = {
    **CANTRIPS,
    **LEVEL_1_SPELLS,
    **LEVEL_2_SPELLS,
    **LEVEL_3_SPELLS,
    **LEVEL_4_SPELLS,
    **LEVEL_5_SPELLS,
    **LEVEL_6_SPELLS,
    **LEVEL_7_SPELLS,
    **LEVEL_8_SPELLS,
    **LEVEL_9_SPELLS
}

__all__ = [

    "SpellAction",
    "SpellEvent",

    "FireBolt",
    "SacredFlame",
    "PoisonSpray",
    "RayOfFrost",
    "AcidSplash",
    "ChillTouch",
    "ShockingGrasp",
    "EldritchBlast",
    "TrueStrike",
    "Guidance",
    "Light",

    "NoHealing",
    "GuidingBoltMarked",
    "PowerWordStunEffect",
    "LightEffect",
    "ContinualFlameObject",
    "GuidanceEffect",
    "ResistanceEffect",
    "ShieldOfFaithEffect",
    "AidEffect",
    "SanctuaryEffect",
    "BeaconOfHopeEffect",
    "DivineWordEffect",
    "AbilityCurseEffect",
    "AttackCurseEffect",
    "InactionCurseEffect",
    "DamageCurseEffect",
    "HeroesFeastObject",
    "HeroesFeastBuff",
    "EatFromFeast",
    "CommandGrovelEffect",
    "CommandHaltEffect",
    "CommandFleeEffect",
    "SilenceZone",
    "GuardianOfFaithObject",
    "GuardianWarded",
    "RegeneratingEffect",

    "MagicMissile",
    "MageArmor",
    "BurningHands",
    "Thunderwave",
    "FalseLife",
    "CharmPerson",
    "Sleep",
    "ColorSpray",
    "GuidingBolt",
    "Grease",
    "FogCloud",
    "Bane",
    "BaneEffect",
    "Bless",
    "BlessEffect",
    "JumpSpell",
    "ExpeditiousRetreat",
    "Command",
    "CureWounds",
    "HealingWord",
    "InflictWounds",
    "ShieldOfFaith",
    "Sanctuary",
    "Resistance",

    "HoldPerson",
    "Shatter",
    "ScorchingRay",
    "Blur",
    "MistyStep",
    "BlindnessDeafness",
    "SpikeGrowth",
    "Web",
    "Invisibility",
    "Darkness",
    "MirrorImage",
    "NecroticBless",
    "DarkvisionSpell",
    "SeeInvisibility",
    "GustOfWind",
    "EnhanceAbility",
    "EnlargeReduce",
    "Silence",
    "ContinualFlame",
    "PrayerOfHealing",
    "LesserRestoration",
    "ProtectionFromPoison",
    "Aid",

    "CallLightning",
    "CallLightningStrike",
    "Fireball",
    "LightningBolt",
    "ProtectionFromEnergy",
    "Fear",
    "HypnoticPattern",
    "SpiritGuardians",
    "Daylight",
    "Slow",
    "Haste",
    "StinkingCloud",
    "SleetStorm",
    "MassHealingWord",
    "BeaconOfHope",
    "RemoveCurse",
    "BestowCurse",

    "Blight",
    "Stoneskin",
    "GreaterInvisibility",
    "IceStorm",
    "DimensionDoor",
    "Banishment",
    "GuardianOfFaith",
    "DeathWard",
    "FreedomOfMovement",

    "HoldMonster",
    "ConeOfCold",
    "Cloudkill",
    "InsectPlague",
    "Telekinesis",
    "FlameStrike",
    "MassCureWounds",
    "GreaterRestoration",

    "CircleOfDeath",
    "Disintegrate",
    "TrueSeeing",
    "Sunbeam",
    "ChainLightning",
    "Eyebite",
    "GlobeOfInvulnerability",
    "HealSpell",
    "Harm",
    "HeroesFeast",

    "PrismaticSpray",
    "FingerOfDeath",
    "Regenerate",
    "DivineWord",

    "Sunburst",
    "PowerWordStun",
    "IncendiaryCloud",
    "AntimagicField",

    "PowerWordKill",
    "MassHeal",

    "CANTRIPS",
    "LEVEL_1_SPELLS",
    "LEVEL_2_SPELLS",
    "LEVEL_3_SPELLS",
    "LEVEL_4_SPELLS",
    "LEVEL_5_SPELLS",
    "LEVEL_6_SPELLS",
    "LEVEL_7_SPELLS",
    "LEVEL_8_SPELLS",
    "LEVEL_9_SPELLS",
    "ALL_SPELLS",

    "register_shield_reaction",
    "register_counterspell_reaction",
    "register_true_strike",
]
