"""
Test event serialization to JSON.

This script verifies that events can be serialized to JSON for websocket transmission.
"""

import json
from uuid import uuid4

from dnd.core.events import (
    Event, EventType,
    SpatialChangeEvent,
    SavingThrowEvent, SkillCheckEvent,
    EventQueue
)

from dnd.core.gridmap import get_map, reset_map
from dnd.entity import Entity, EntityConfig


def test_serialize_event(event: Event, name: str) -> bool:
    """Test that an event can be serialized to JSON."""
    print(f"\n=== {name} ===")
    try:
        # Method 1: model_dump with json mode
        data = event.model_dump(mode='json')
        print(f"  model_dump(mode='json'): OK ({len(data)} keys)")

        # Method 2: Convert to JSON string
        json_str = json.dumps(data)
        print(f"  json.dumps(): OK ({len(json_str)} chars)")

        # Method 3: model_dump_json (pydantic's native)
        json_str2 = event.model_dump_json()
        print(f"  model_dump_json(): OK ({len(json_str2)} chars)")

        # Show a sample of the data
        print(f"  Sample keys: {list(data.keys())[:5]}...")

        return True
    except Exception as e:
        print(f"  ERROR: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_basic_events():
    """Test serialization of basic event types."""
    print("\n" + "=" * 60)
    print("BASIC EVENT SERIALIZATION")
    print("=" * 60)

    results = []

    # Basic Event
    event1 = Event(
        source_entity_uuid=uuid4(),
        event_type=EventType.BASE_ACTION,
        use_register=False  # Don't register, just test serialization
    )
    results.append(test_serialize_event(event1, "Basic Event"))

    # SpatialChangeEvent - entity entered
    event2 = SpatialChangeEvent.entity_entered(
        position=(5, 5),
        entity_uuid=uuid4(),
        old_position=(3, 3)
    )
    results.append(test_serialize_event(event2, "SpatialChangeEvent (entered)"))

    # SpatialChangeEvent - tile changed
    event3 = SpatialChangeEvent.tile_changed(
        position=(2, 2),
        walkable=False,
        visible=True
    )
    results.append(test_serialize_event(event3, "SpatialChangeEvent (tile)"))

    return all(results)


def test_complex_events():
    """Test serialization of events with complex fields."""
    print("\n" + "=" * 60)
    print("COMPLEX EVENT SERIALIZATION")
    print("=" * 60)

    results = []

    # SavingThrowEvent
    event1 = SavingThrowEvent(
        source_entity_uuid=uuid4(),
        target_entity_uuid=uuid4(),
        ability_name="dexterity",
        dc=15,
        use_register=False
    )
    results.append(test_serialize_event(event1, "SavingThrowEvent"))

    # SkillCheckEvent
    event2 = SkillCheckEvent(
        source_entity_uuid=uuid4(),
        target_entity_uuid=uuid4(),
        skill_name="stealth",
        dc=12,
        use_register=False
    )
    results.append(test_serialize_event(event2, "SkillCheckEvent"))

    return all(results)


def test_events_from_actions():
    """Test serialization of events generated by actual game actions."""
    print("\n" + "=" * 60)
    print("EVENTS FROM GAME ACTIONS")
    print("=" * 60)

    # Clear state
    reset_map()
    Entity._entity_registry.clear()
    Entity._entity_by_position.clear()

    # Create a simple grid
    grid = get_map()
    grid.create_rectangle(0, 0, 10, 10)

    # Create an entity (this will generate spatial events)
    entity_uuid = uuid4()
    _ = Entity.create(
        source_entity_uuid=entity_uuid,
        name="TestEntity",
        config=EntityConfig(position=(3, 3))
    )

    # Get events from queue
    all_events = EventQueue._all_events
    print(f"\nTotal events in queue: {len(all_events)}")

    results = []
    for i, event in enumerate(all_events[-5:]):  # Last 5 events
        results.append(test_serialize_event(event, f"Queue Event {i+1}: {event.event_type.value}"))

    return all(results) if results else True


def test_event_field_types():
    """Inspect event field types to identify potential serialization issues."""
    print("\n" + "=" * 60)
    print("EVENT FIELD TYPE INSPECTION")
    print("=" * 60)

    event_classes = [Event, SpatialChangeEvent, SavingThrowEvent, SkillCheckEvent]

    for cls in event_classes:
        print(f"\n{cls.__name__} fields:")
        for name, field in cls.model_fields.items():
            annotation = str(field.annotation)
            # Flag potentially problematic types
            warning = ""
            if "Callable" in annotation or "function" in annotation:
                warning = " ⚠️ CALLABLE"
            elif "ModifiableValue" in annotation:
                warning = " ⚠️ COMPLEX"
            print(f"  {name}: {annotation[:50]}{warning}")


def main():
    """Run all serialization tests."""
    print("=" * 60)
    print("EVENT SERIALIZATION TEST")
    print("=" * 60)

    # Inspect field types first
    test_event_field_types()

    # Run serialization tests
    results = [
        test_basic_events(),
        test_complex_events(),
        test_events_from_actions(),
    ]

    print("\n" + "=" * 60)
    print("RESULTS")
    print("=" * 60)

    if all(results):
        print("✓ All serialization tests passed!")
        return True
    else:
        print("✗ Some serialization tests failed")
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
