"""Agent framework for the D&D engine."""

from ai.agents.base import BaseAgent, BehaviorTreeAgent, UtilityAgent
from ai.composites import (
    CompositeAction,
    CompositeResult,
    DashToward,
    FocusFire,
    InterruptPolicy,
    InterruptType,
    MoveAndAttack,
    Retreat,
    detect_interrupts,
)
from ai.interface import GameInterface, LocalGameInterface
from ai.models import (
    ActionEconomy,
    ActionOption,
    ActionResult,
    AttackData,
    DiceSpec,
    SpellData,
    TacticalEntity,
    TacticalState,
    TargetOption,
    action_ev,
    attack_ev,
    crit_chance,
    hit_chance,
    spell_attack_ev,
    spell_save_ev,
)

__all__ = [
    "ActionEconomy",
    "ActionOption",
    "ActionResult",
    "AttackData",
    "BaseAgent",
    "BehaviorTreeAgent",
    "CompositeAction",
    "CompositeResult",
    "DashToward",
    "DiceSpec",
    "FocusFire",
    "GameInterface",
    "InterruptPolicy",
    "InterruptType",
    "LocalGameInterface",
    "MoveAndAttack",
    "Retreat",
    "SpellData",
    "TacticalEntity",
    "TacticalState",
    "TargetOption",
    "UtilityAgent",
    "action_ev",
    "attack_ev",
    "crit_chance",
    "detect_interrupts",
    "hit_chance",
    "spell_attack_ev",
    "spell_save_ev",
]
