# generated by datamodel-codegen:
#   filename:  python-type-schema.json

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class HealthResponse(TypedDict):
    kind: NotRequired[Literal['health']]
    status: NotRequired[Literal['ok']]


class BoundaryState(TypedDict):
    lifecycle: Literal[
        'starting',
        'waiting_for_human',
        'advancing',
        'delivery_blocked',
        'terminal',
        'failed',
        'closing',
        'closed',
    ]
    input_actor_uuid: str | None
    state_revision: str | None
    reason: NotRequired[
        Literal[
            'recording_capacity',
            'catch_up',
            'reader_backpressure',
            'worker_failure',
            'capture_failure',
            'contract_failure',
            'recording_failure',
            'host_close',
        ]
        | None
    ]
    incident_id: NotRequired[str | None]


class PlayerAudience(TypedDict):
    controlled: list[str]
    observers: list[str]
    revision: NotRequired[int]


class PlayerCursor(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    sequence: int


class ProtocolIdentity(TypedDict):
    protocol_version: NotRequired[Literal[1]]
    player_schema_version: NotRequired[Literal[4]]
    schema_digest: str


class StatusSnapshot(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    boundary: BoundaryState
    published_cursor: PlayerCursor | None
    final_cursor: PlayerCursor | None
    attachment_epoch: str | None
    catch_up_cursor: PlayerCursor | None
    acknowledged_cursor: PlayerCursor | None
    next_command_number: int
    pending_command_numbers: list[int]


class BootstrapResponse(TypedDict):
    kind: NotRequired[Literal['bootstrap']]
    protocol: ProtocolIdentity
    status: StatusSnapshot
    audience: PlayerAudience | None
    encounter_name: str
    content_revision: str | None


class StatusResponse(TypedDict):
    kind: NotRequired[Literal['status']]
    status: StatusSnapshot


class AttachmentRequest(TypedDict):
    acquisition_id: str
    expected_attachment_epoch: str | None


class AttachmentResponse(TypedDict):
    kind: NotRequired[Literal['attachment']]
    acquisition_id: str
    attachment_epoch: str
    status: StatusSnapshot


class ActionLogData(TypedDict):
    kind: NotRequired[Literal['action']]
    entity_name: str
    entity_uuid: str
    action_name: str
    effect_description: str
    target_name: NotRequired[str | None]
    target_uuid: NotRequired[str | None]


class ActionReaction(TypedDict):
    triggered_lineage_uuid: str | None
    succeeded: bool
    automatic: bool


class AppearanceConfig(TypedDict):
    portrait_key: NotRequired[str | None]
    presentation_kind: NotRequired[Literal['layered', 'placeholder']]
    visual_scale: NotRequired[float]
    visual_scale_x: NotRequired[float]
    placeholder_tint: NotRequired[int]
    body_category: NotRequired[Literal['NakedBody', 'NakedBody2', 'NakedBody3']]
    skin_tint: NotRequired[int]
    head_category: NotRequired[
        Literal['Head1', 'Head9', 'Head10', 'Head16', 'Head17', 'Head22'] | None
    ]
    hair_tint: NotRequired[int]
    has_beard: NotRequired[bool]
    beard_tint: NotRequired[int]


class ApplicationMembership(TypedDict):
    lineage_uuid: str
    application_id: str
    index: int


class ApplicationResolutionRef(TypedDict):
    kind: NotRequired[Literal['application']]
    lineage_uuid: str
    application_id: str


type BaseAbilityScore = int


type FlexibleAbilityBonus = int


type NewlyReachedPosition = int


class AreaReachFact(TypedDict):
    kind: NotRequired[Literal['area_reach']]
    stage_index: int
    newly_reached_positions: list[list[NewlyReachedPosition]]
    previous_reach_lineage_uuid: str | None
    prerequisite_destruction_lineages: list[str]


type TargetPositionItem = int


type AttackOutcome = Literal['Hit', 'Miss', 'Crit', 'Crit Miss']


class AvailableHandlerInfo(TypedDict):
    name: str
    behavior_id: str
    provided_by_id: str
    origin_root_id: NotRequired[str | None]
    uuid: str
    enabled: bool
    trigger_event: str


type Background = Literal['background.acolyte', 'background.adventurer']


type Position = int


type PositionItem = int


type DepositedPositionItem = int


type BoundaryStructureKind = Literal[
    'cliff', 'embankment', 'retaining_wall', 'wall', 'door', 'fence'
]


type CardinalDirection = Literal['north', 'south', 'east', 'west']


type CharacterClass = Literal['class.barbarian', 'class.fighter', 'class.sorcerer']


type CharacterSubclass = Literal[
    'subclass.barbarian.berserker',
    'subclass.fighter.champion',
    'subclass.sorcerer.draconic_bloodline',
]


class ClassChoiceSelection(TypedDict):
    choice_id: str
    values: list[str]


type CombatLogEntryType = Literal[
    'attack',
    'movement',
    'action',
    'saving_throw',
    'skill_check',
    'condition_applied',
    'condition_removed',
    'damage_taken',
    'heal',
    'death',
    'turn_start',
    'turn_end',
    'multi_entity_action',
    'spell_save',
    'spell_damage',
    'spell_interruption',
    'entity_spotted',
    'hazard_detected',
    'roll_modification',
    'spatial_effect',
]


type ConditionAgencyDenial = Literal['none', 'full_turn']


type ConditionCategory = Literal['condition', 'status', 'internal']


type ConditionRemovalTrigger = Literal['positive_damage_applied', 'shake_awake']


class ConditionRemovedLogData(TypedDict):
    kind: NotRequired[Literal['condition_removed']]
    condition_name: str
    reveals_target: bool


type ConditionTag = Literal[
    'magical',
    'curse',
    'disease',
    'poison',
    'exhaustion',
    'petrification',
    'ability_score_reduction',
    'hit_point_maximum_reduction',
    'concentration',
]


type OriginItem = int


type DirectionItem = int


class ConePresentationGeometry(TypedDict):
    shape: NotRequired[Literal['cone']]
    origin: list[OriginItem]
    direction: list[DirectionItem]
    length_feet: int
    angle_degrees: int


type ConnectorActionCostType = Literal['actions', 'bonus_actions']


type StartPositionItem = int


type EndPositionItem = int


type PathItem = int


type RequestedEndPositionItem = int


type ObjectiveEndPositionItem = int


type ConnectorProvocationPolicy = Literal['provokes_source_exit', 'does_not_provoke']


type ContactPassage = Literal[
    'structural', 'clear', 'blocked', 'light_weapons', 'hand_and_light_weapons'
]


type ContentDefinitionKind = Literal[
    'item',
    'creature',
    'action',
    'spell',
    'condition',
    'trait',
    'reaction',
    'feat',
    'class_feature',
    'class',
    'subclass',
    'species',
    'species_variant',
    'background',
    'starting_equipment_package',
    'environment_object',
    'rule_primitive',
]


class ContentOrdering(TypedDict):
    sort_group: NotRequired[str]
    sort_order: NotRequired[int]


class ContentRef(TypedDict):
    pack_id: str
    definition_kind: ContentDefinitionKind
    content_id: str
    content_version: int
    definition_contract_hash: str


type ContentVisibility = Literal['public', 'observed', 'developer', 'internal']


class CubePresentationGeometry(TypedDict):
    shape: NotRequired[Literal['cube']]
    origin: list[OriginItem]
    direction: NotRequired[list[DirectionItem] | None]
    size_feet: int
    centered: bool


type CenterItem = int


class CylinderPresentationGeometry(TypedDict):
    shape: NotRequired[Literal['cylinder']]
    center: list[CenterItem]
    radius_feet: int
    height_feet: int


class DamageTakenLogData(TypedDict):
    kind: NotRequired[Literal['damage_taken']]
    target_name: str
    damage: int
    damage_type: str
    source_name: str
    effect_id: NotRequired[str | None]
    blocked: NotRequired[bool | None]
    blocked_reason: NotRequired[str | None]


type DamageType = Literal[
    'Acid',
    'Bludgeoning',
    'Cold',
    'Fire',
    'Force',
    'Lightning',
    'Necrotic',
    'Piercing',
    'Poison',
    'Psychic',
    'Radiant',
    'Slashing',
    'Thunder',
]


class DeathLogData(TypedDict):
    kind: NotRequired[Literal['death']]
    entity_name: str
    final_hp: int


class DeathSaveFact(TypedDict):
    kind: NotRequired[Literal['death_save']]
    entity_uuid: str
    natural_roll: int | None
    succeeded: bool


class DeathSaveLogData(TypedDict):
    kind: NotRequired[Literal['death_save']]
    entity_name: str
    entity_uuid: str
    roll: int
    natural_roll: int
    dc: int
    successes: int
    failures: int
    became_stable: bool
    regained_hit_point: bool
    died: bool


class DiceRollDisplay(TypedDict):
    dice_str: str
    results: NotRequired[list[int]]
    bonus: NotRequired[int]
    total: int
    all_d20_rolls: NotRequired[list[int] | None]
    d20_used: NotRequired[int | None]
    advantage_status: NotRequired[str | None]


type DoorMechanism = Literal['single_hinged', 'double_hinged', 'lift']


type DoorSwing = Literal['inward', 'outward']


type DurationType = Literal['rounds', 'permanent', 'until_long_rest', 'on_condition']


class EffectEndpoint(TypedDict):
    kind: Literal['creature', 'object']
    uuid: str
    position: list[PositionItem]
    base_height_steps: int


class EffectPropagationLink(TypedDict):
    source: EffectEndpoint
    target: EffectEndpoint
    application_id: str


type ElevationSurfaceKind = Literal['ordinary', 'stairs', 'ramp']


class EmptyLogData(TypedDict):
    kind: NotRequired[Literal['empty']]


class EntitySpottedLogData(TypedDict):
    kind: NotRequired[Literal['entity_spotted']]
    observer_name: str
    observer_uuid: str
    target_name: str
    target_uuid: str
    target_position: list[TargetPositionItem] | None
    passive_perception: int
    stealth_dc: int


type EquipmentRenderLayer = Literal[
    'backpack',
    'cloak',
    'belt',
    'chest',
    'hands',
    'helmet',
    'legs',
    'offhand',
    'shoes',
    'weapon',
]


type EquippedVisualPolicy = Literal['visible', 'hidden']


type EventPhase = Literal['declaration', 'execution', 'effect', 'completion', 'cancel']


class EventResolutionRef(TypedDict):
    kind: NotRequired[Literal['event']]
    lineage_uuid: str


type EventType = Literal[
    'base_action',
    'attack',
    'movement',
    'step_movement',
    'forced_movement',
    'portal_transfer',
    'mechanism_activation',
    'ability_check',
    'saving_throw',
    'skill_check',
    'inflicted_damage',
    'take_damage',
    'damage_applied',
    'heal',
    'temporary_hit_points_changed',
    'cast_spell',
    'attack_miss',
    'attack_hit',
    'attack_critical',
    'condition_application',
    'condition_removal',
    'condition_state_changed',
    'weapon_equip',
    'weapon_unequip',
    'armor_equip',
    'armor_unequip',
    'shield_equip',
    'shield_unequip',
    'item_location_state',
    'item_holdings_released',
    'item_destruction',
    'item_charge_consumption',
    'world_initialized',
    'world_modified',
    'entity_created',
    'entity_faction_changed',
    'summon_admission',
    'entity_level_added',
    'entity_level_removed',
    'trigger_event',
    'dice_roll',
    'd20_roll_result',
    'attack_d20_roll',
    'save_d20_roll',
    'check_d20_roll',
    'damage_roll_result',
    'heal_roll_result',
    'enemy_spotted',
    'enemy_killed',
    'enemy_engaged',
    'spatial_entity_entered',
    'spatial_entity_left',
    'spatial_tile_changed',
    'spatial_object_placed',
    'spatial_object_removed',
    'spatial_perceivability_changed',
    'spatial_light_changed',
    'spatial_object_changed',
    'traversal_connector_changed',
    'movement_collision',
    'sensory_update',
    'spatial_effect_changed',
    'spatial_effect_interaction',
    'area_reached',
    'fire_exposure',
    'exposed_flame_ignited',
    'wind_exposure',
    'encounter_start',
    'encounter_end',
    'round_start',
    'round_end',
    'turn_start',
    'turn_end',
    'life_state_change',
    'revive',
    'death_save',
    'instant_death',
    'death',
]


class FactionFact(TypedDict):
    kind: NotRequired[Literal['faction']]
    entity_uuid: str
    faction_after: str | None
    control_lost: NotRequired[bool]


class FontConversion(TypedDict):
    direction: Literal['slot_to_points', 'points_to_slot']
    slot_level: NotRequired[int | None]
    sorcery_points_delta: NotRequired[int | None]
    spell_slots_delta: NotRequired[int | None]


type DisclosedPathItem = int


class ForcedMovementLogData(TypedDict):
    kind: NotRequired[Literal['forced_movement']]
    type: NotRequired[Literal['forced_movement']]
    cause: str
    direction: list[DirectionItem]
    intended_distance: int
    actual_distance: int
    blocked: bool
    blocked_by: str | None
    start_position: list[StartPositionItem] | None
    end_position: list[EndPositionItem] | None


type HandlerDispatchOutcome = Literal[
    'no_effect', 'emitted_events', 'modified_event', 'canceled_event'
]


class HazardDetectedLogData(TypedDict):
    kind: NotRequired[Literal['hazard_detected']]
    observer_name: str
    observer_uuid: str
    hazard_name: str
    position: list[PositionItem] | None
    passive_perception: int
    stealth_dc: int


class HealFact(TypedDict):
    kind: NotRequired[Literal['heal']]
    source_entity_uuid: str | None
    target_entity_uuid: str
    actual_healing: int
    was_blocked: bool
    resulting_normal_hp: int | None
    resulting_temporary_hp: int | None
    source_condition_uuid: NotRequired[str | None]


class HealLogData(TypedDict):
    kind: NotRequired[Literal['heal']]
    entity_name: str
    entity_uuid: str
    amount: int
    source_description: str


class IndomitableReroll(TypedDict):
    condition_uuid: NotRequired[str | None]
    succeeded: bool


class ItemConcentrationSlot(TypedDict):
    slot_uuid: str
    cast_lineage_uuid: NotRequired[str | None]
    spell_id: NotRequired[str | None]
    spell_name: str


class ItemEffectChangeFact(TypedDict):
    kind: NotRequired[Literal['item_effect']]
    item_uuid: str
    effect_uuid: str
    event_type: EventType


type ItemIntegrity = Literal['intact', 'destroyed']


type ItemPresentationKind = Literal['item', 'usable', 'weapon', 'armor', 'shield']


type ItemRarity = Literal['common', 'uncommon', 'rare', 'very_rare', 'legendary']


type ItemResourceChange = Literal['consume', 'recharge']


class JumpMovementLogData(TypedDict):
    entity_name: str
    entity_uuid: str
    start_position: list[StartPositionItem]
    end_position: list[EndPositionItem]
    path: NotRequired[list[list[PathItem]]]
    distance_feet: NotRequired[int]
    movement_cost: NotRequired[int]
    requested_end_position: NotRequired[list[RequestedEndPositionItem] | None]
    termination_reason: NotRequired[str]
    controller_revalidation: NotRequired[bool]
    controller_revalidation_reason: NotRequired[str | None]
    kind: NotRequired[Literal['jump_movement']]
    movement_type: NotRequired[Literal['jump']]
    objective_end_position: list[ObjectiveEndPositionItem]
    start_elevation_feet: int
    requested_end_elevation_feet: int
    end_elevation_feet: int


type LandingKind = Literal['ground', 'fall', 'controlled', 'impact']


type LifeState = Literal['alive', 'dying', 'stable', 'dead']


type LifeStateChangeReason = Literal[
    'damage',
    'massive_damage',
    'instant_death',
    'death_save_failures',
    'stabilization',
    'healing',
    'revival',
    'direct_state_check',
]


type LightLevel = Literal[0, 1, 2, 3, 4]


class LinePresentationGeometry(TypedDict):
    shape: NotRequired[Literal['line']]
    origin: list[OriginItem]
    direction: list[DirectionItem]
    length_feet: int
    width_feet: int


type Material = Literal[
    'earth',
    'sand',
    'stone',
    'wood',
    'metal',
    'fabric',
    'glass',
    'water',
    'ice',
    'vegetation',
]


class MaterialDepositSource(TypedDict):
    deposit_uuid: str
    origin: list[OriginItem]
    radius_cells: int


type OriginPositionItem = int


type AffectedPosition = int


class MechanismActivationFact(TypedDict):
    kind: NotRequired[Literal['mechanism_activation']]
    mechanism_uuid: str | None
    mechanism_content_id: str
    target_entity_uuid: str | None
    origin_position: list[OriginPositionItem] | None
    direction: list[DirectionItem]
    affected_positions: list[list[AffectedPosition]]
    end_position: list[EndPositionItem] | None
    committed: bool


class ModifierBreakdown(TypedDict):
    name: str
    value: int
    source: NotRequired[str]


class MovementLogData(TypedDict):
    entity_name: str
    entity_uuid: str
    start_position: list[StartPositionItem]
    end_position: list[EndPositionItem]
    path: NotRequired[list[list[PathItem]]]
    distance_feet: NotRequired[int]
    movement_cost: NotRequired[int]
    requested_end_position: NotRequired[list[RequestedEndPositionItem] | None]
    termination_reason: NotRequired[str]
    controller_revalidation: NotRequired[bool]
    controller_revalidation_reason: NotRequired[str | None]
    kind: NotRequired[Literal['movement']]


type MovementMode = Literal['walking', 'flying', 'swimming', 'burrowing']


type MovementProvocationPolicy = Literal['ordinary_exit', 'does_not_provoke']


type MovementTrajectory = Literal['path', 'direct_arc', 'connector_transfer']


type TargetEntryIndice = int


type AoeCenterItem = int


class MultiEntityLogData(TypedDict):
    kind: NotRequired[Literal['multi_entity_action']]
    action_name: str
    caster_name: str
    total_targets: NotRequired[int]
    target_names: NotRequired[list[str]]
    total_damage: NotRequired[int]
    per_target_damage: NotRequired[list[int]]
    saves_succeeded: NotRequired[int]
    saves_failed: NotRequired[int]
    target_entry_indices: NotRequired[list[TargetEntryIndice]]
    aoe_shape: NotRequired[str | None]
    aoe_center: NotRequired[list[AoeCenterItem] | None]


class ObjectDamageFact(TypedDict):
    kind: NotRequired[Literal['object_damage']]
    object_uuid: str
    applied_damage: int
    resulting_hp: int
    damage_type: DamageType | None


class ObjectResidueState(TypedDict):
    condition_uuid: str
    residue_id: str
    description: str
    faces: list[CardinalDirection]


type MinimumPositionItem = int


class ObjectSectionVolume(TypedDict):
    minimum_position: list[MinimumPositionItem]
    base_height_steps: int


class ObservedChangeRef(TypedDict):
    source_event_uuid: str
    source_index: int
    resolution_ref: NotRequired[EventResolutionRef | ApplicationResolutionRef | None]
    field: Literal[
        'position',
        'visibility',
        'light',
        'hazards',
        'senses',
        'paths',
        'entity_contact',
        'object_contact',
        'spatial_effect',
    ]
    owner_uuid: str


type ObservedPathSegment = int


class ObservedMovementLogData(TypedDict):
    kind: NotRequired[Literal['observed_movement']]
    type: NotRequired[Literal['movement']]
    entity_name: str
    entity_uuid: str
    movement_type: NotRequired[str | None]
    observation_complete: bool
    observed_path_segments: list[list[list[ObservedPathSegment]]]
    observed_distance_feet: float
    start_position: NotRequired[list[StartPositionItem] | None]
    end_position: NotRequired[list[EndPositionItem] | None]
    path: NotRequired[list[list[PathItem]]]
    distance_feet: NotRequired[float | None]
    movement_cost: NotRequired[float | None]


type OccupancyLayer = Literal['ground', 'air', 'underground']


class OriginChoiceSelection(TypedDict):
    choice_id: str
    values: list[str]


class OutcomeProtection(TypedDict):
    protection_id: str
    blocked_effect_ids: NotRequired[list[str]]


type AnchorPositionItem = int


type VisibleVolumePosition = int


type LastVisualPositionItem = int


type Ability = int


class PlayerResource(TypedDict):
    key: str
    label: str
    current: int
    maximum: int


type Bound = int


class PlayerWorld(TypedDict):
    battlefield_id: str
    battlefield_name: str
    bounds: list[Bound]
    width: int
    height: int


class PortalTransferFact(TypedDict):
    kind: NotRequired[Literal['portal_transfer']]
    target_entity_uuid: str
    portal_uuid: str | None
    start_position: list[StartPositionItem] | None
    end_position: list[EndPositionItem] | None
    committed: bool
    portal_content_id: NotRequired[str | None]


class RelentlessRageIntervention(TypedDict):
    condition_uuid: NotRequired[str | None]
    succeeded: bool


type RemainsDisposition = Literal['intact', 'disintegrated']


class ResidueEllipse(TypedDict):
    center: list[float]
    radius_x: float
    radius_y: float
    angle: NotRequired[float]


class RollModificationLogFact(TypedDict):
    operation: Literal['replace', 'append']
    handler_name: str
    packet_index: NotRequired[int | None]
    previous_total: NotRequired[int | None]
    final_total: int
    reason: str
    packet_damage_type: NotRequired[str | None]
    packet_dice: NotRequired[str | None]


class SavingThrowFact(TypedDict):
    kind: NotRequired[Literal['saving_throw']]
    target_entity_uuid: str
    ability_name: Literal[
        'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma'
    ]
    succeeded: bool
    effect_id: str | None
    indomitable_reroll: NotRequired[IndomitableReroll | None]


class SavingThrowLogData(TypedDict):
    kind: NotRequired[Literal['saving_throw']]
    entity_name: str
    entity_uuid: str
    ability: str
    dc: int
    roll: DiceRollDisplay
    bonus_breakdown: NotRequired[list[ModifierBreakdown]]
    advantage_breakdown: NotRequired[list[ModifierBreakdown]]
    success: bool
    source_name: NotRequired[str | None]


type SensesType = Literal[
    'Blindsight',
    'Darkvision',
    'Tremorsense',
    'Truesight',
    'Devils Sight',
    'See Invisible',
]


type ObserverPositionItem = int


type VisibleCellsAddedItem = int


type VisibleCellsRemovedItem = int


type SeenCellsAddedItem = int


class ShoveFact(TypedDict):
    kind: NotRequired[Literal['shove']]
    source_entity_uuid: str
    target_entity_uuid: str
    behavior_id: str | None
    contest_success: bool | None
    push_distance: int
    knocked_prone: bool


type PushDirectionItem = int


class ShoveLogData(TypedDict):
    kind: NotRequired[Literal['shove']]
    action_type: NotRequired[Literal['shove']]
    target_weight: int
    max_shove_weight: int
    contest_success: bool | None
    push_distance: int
    push_direction: list[PushDirectionItem]
    end_position: list[EndPositionItem] | None
    knocked_prone: bool
    blocked_by: str | None
    is_ally: bool


type Size = Literal['Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan']


class SkillCheckLogData(TypedDict):
    kind: NotRequired[Literal['skill_check']]
    entity_name: str
    entity_uuid: str
    skill: str
    dc: NotRequired[int | None]
    roll: DiceRollDisplay
    bonus_breakdown: NotRequired[list[ModifierBreakdown]]
    advantage_breakdown: NotRequired[list[ModifierBreakdown]]
    success: NotRequired[bool | None]


type SlopeAxis = Literal['north_south', 'east_west']


type SpatialChangeType = Literal[
    'entity_entered',
    'entity_left',
    'tile_changed',
    'tile_created',
    'tile_removed',
    'object_placed',
    'object_removed',
    'perceivability_changed',
    'light_changed',
    'object_changed',
    'movement_collision',
]


class SpatialDamageSource(TypedDict):
    spatial_effect_uuid: str
    position: list[PositionItem]
    target_position: list[TargetPositionItem]
    base_height_steps: int
    exposure: Literal['contact', 'radiated_heat']


type SpatialDisposition = Literal['present', 'absent', 'return_pending', 'home_plane']


type SpatialEffectChangeOperation = Literal[
    'created',
    'footprint_changed',
    'revealed',
    'state_changed',
    'removed',
    'transformed',
]


type SpatialEffectInteractionOperation = Literal[
    'ignite', 'douse', 'freeze', 'electrify', 'vaporize', 'disperse'
]


type SpatialEffectLayer = Literal['ground_surface', 'cloud', 'field']


type RemovedPosition = int


class SpatialInteractionLogData(TypedDict):
    kind: NotRequired[Literal['spatial_interaction']]
    operation: SpatialEffectInteractionOperation
    intensity: Literal['minor', 'moderate', 'strong']
    affected_positions: list[list[AffectedPosition]]
    source_item_id: str | None


type Species = Literal[
    'species.dragonborn',
    'species.dwarf',
    'species.elf',
    'species.gnome',
    'species.half_elf',
    'species.half_orc',
    'species.halfling',
    'species.human',
    'species.tiefling',
]


type SpeciesVariant = Literal[
    'species_variant.dwarf.hill',
    'species_variant.elf.high',
    'species_variant.gnome.rock',
    'species_variant.halfling.lightfoot',
]


class SpellDamageLogData(TypedDict):
    kind: NotRequired[Literal['spell_damage']]
    spell_name: str
    target_name: str
    damage: int
    damage_type: str


type SourcePositionItem = int


type AoePositionItem = int


type ResolvedAreaPosition = int


class SpellInterruptionLogData(TypedDict):
    kind: NotRequired[Literal['spell_interruption']]
    outcome_code: str
    counterspeller_name: str
    counterspeller_uuid: str
    original_caster_name: str
    original_caster_uuid: str
    spell_name: str
    incoming_spell_level: int
    counterspell_slot_level: int
    automatic: bool
    check_total: NotRequired[int | None]
    check_dc: NotRequired[int | None]
    succeeded: bool


class SpherePresentationGeometry(TypedDict):
    shape: NotRequired[Literal['sphere']]
    center: list[CenterItem]
    radius_feet: int


type FromPositionItem = int


type ToPositionItem = int


class StepFact(TypedDict):
    kind: NotRequired[Literal['step']]
    source_entity_uuid: str
    from_position: list[FromPositionItem]
    to_position: list[ToPositionItem]
    from_elevation_feet: int
    to_elevation_feet: int
    disclosed_path: list[list[DisclosedPathItem]]
    trajectory: MovementTrajectory
    provocation_policy: MovementProvocationPolicy
    committed: bool
    resolved_speed_feet: NotRequired[int | None]
    movement_mode: NotRequired[MovementMode | None]
    from_layer: NotRequired[OccupancyLayer | None]
    to_layer: NotRequired[OccupancyLayer | None]


class StepMovementLogData(TypedDict):
    kind: NotRequired[Literal['step_movement']]
    type: NotRequired[Literal['step_movement']]
    from_position: list[FromPositionItem]
    to_position: list[ToPositionItem]
    path_index: int
    movement_cost: float
    trajectory: MovementTrajectory
    disclosed_path: list[list[DisclosedPathItem]]
    from_elevation_feet: int
    to_elevation_feet: int
    provocation_policy: MovementProvocationPolicy
    committed: bool


type SummonDepartureCause = Literal[
    'expired', 'dismissed', 'defeated', 'sustain_lost', 'closed'
]


type SummonManifestation = Literal['natural', 'fey_spirit', 'fiend']


class SurfaceLayer(TypedDict):
    material: Material
    description: NotRequired[str]


class TemporaryHitPointsGrant(TypedDict):
    instance_uuid: str
    source_id: NotRequired[str | None]


class TileSurface(TypedDict):
    base_material: Material
    layers: NotRequired[list[SurfaceLayer]]
    description: NotRequired[str]


type TrapState = Literal['ready', 'activated', 'deactivated']


type TraversalConnectorKind = Literal[
    'ladder', 'rope', 'lift', 'vertical_stairs', 'passage'
]


class TurnFact(TypedDict):
    kind: NotRequired[Literal['turn']]
    event_type: EventType
    entity_uuid: str | None
    round_number: int | None


class TurnLogData(TypedDict):
    kind: NotRequired[Literal['turn']]
    entity_name: str
    entity_uuid: str
    round_number: int
    turn_index: int | None


class UnknownMovementLogData(TypedDict):
    kind: NotRequired[Literal['unknown_movement']]
    type: NotRequired[Literal['movement']]
    observed: NotRequired[Literal[True]]


class UnlocatedMovementLogData(TypedDict):
    kind: NotRequired[Literal['unlocated_movement']]
    type: NotRequired[Literal['movement']]
    observation_complete: NotRequired[Literal[False]]


class VersionRow(TypedDict):
    source_index: int
    event_uuid: str
    lineage_uuid: str


type VisualLoadoutSlot = Literal[
    'weapon_melee_main',
    'weapon_melee_off',
    'weapon_ranged_main',
    'weapon_ranged_off',
    'helmet',
    'body_armor',
    'gauntlets',
    'greaves',
    'boots',
    'amulet',
    'cloak',
    'backpack',
    'ring_left',
    'ring_right',
]


type LowerHeightPlane = list[float]


class VolumeSurfaceSight(TypedDict):
    position: list[PositionItem]
    lower_height_planes: list[LowerHeightPlane]


class WallDome(TypedDict):
    form: NotRequired[Literal['dome']]
    center: list[float]
    radius_feet: float


type Point = list[float]


class WallPolyline(TypedDict):
    form: NotRequired[Literal['polyline']]
    points: list[Point]


class WallRing(TypedDict):
    form: NotRequired[Literal['ring']]
    center: list[float]
    radius_feet: float


class WallSegment(TypedDict):
    form: NotRequired[Literal['segment']]
    start: list[float]
    end: list[float]


type WeaponSet = Literal['none', 'melee', 'ranged']


type WeaponSlot = Literal['MELEE_MAIN', 'MELEE_OFF', 'RANGED_MAIN', 'RANGED_OFF']


type EndpointItem = int


type Endpoint = list[EndpointItem]


type Endpoint1Item = int


type Endpoint1 = list[Endpoint1Item]


type EndpointElevationsfoot = int


class WorldConnectorState(TypedDict):
    connector_uuid: str
    authored_id: str
    kind: TraversalConnectorKind
    presentation_key: str
    endpoints: list[Endpoint | Endpoint1]
    support_tile_uuids: list[str]
    endpoint_elevations_feet: list[EndpointElevationsfoot]
    movement_cost_feet: int
    action_cost_type: NotRequired[ConnectorActionCostType | None]
    action_cost_amount: NotRequired[int]
    bidirectional: bool
    enabled: bool
    provocation_policy: ConnectorProvocationPolicy


type WorldEdgeChannel = Literal['movement', 'optical', 'propagation']


type RemovedBand = int


class WorldObjectSupport(TypedDict):
    position: list[PositionItem]
    tile_uuid: str


type WorldPlacementKind = Literal['center', 'boundary']


class AckRequest(TypedDict):
    cursor: PlayerCursor


class AckResponse(TypedDict):
    kind: NotRequired[Literal['ack']]
    cursor: PlayerCursor
    catch_up_cursor: PlayerCursor


class ChoicesRequest(TypedDict):
    actor_uuid: str
    state_revision: str
    force_attack: bool
    correlation_id: str


class ActionAffordance(TypedDict):
    surface: NotRequired[Literal['action_bar', 'world', 'inventory']]
    binding: NotRequired[Literal['target', 'source_item', 'connector']]
    default_priority: NotRequired[int]


type ActionAvailabilityStatus = Literal[
    'available',
    'source_unaffordable',
    'requirements_unmet',
    'no_valid_targets',
    'target_cost_unaffordable',
]


type ActionCategory = Literal['ability', 'attack', 'spell', 'movement']


type ActionInformationOperation = Literal[
    'reveal_region', 'change_light', 'grant_sense', 'conceal_region'
]


type ActionSetupDuration = Literal['current_turn', 'until_next_turn', 'until_removed']


type ActionSetupMaintenanceFailure = Literal['remove_setup']


type ActionSetupMaintenanceTrigger = Literal['revealing_action']


type ActionTopologyOperation = Literal['create_blocker', 'remove_blocker']


class ActionVariantFacet(TypedDict):
    key: Literal[
        'form', 'side', 'radius', 'ability', 'damage_type', 'movement', 'width', 'rank'
    ]
    value: str
    label: str


type ActionWorldEffectAnchor = Literal[
    'actor', 'selected_target', 'selected_position', 'selected_object'
]


type ActionWorldEffectCertainty = Literal['guaranteed', 'conditional']


type ActionWorldEffectScope = Literal[
    'target', 'region', 'frontier', 'magical_darkness', 'hazard_region'
]


type ActionWorldEffectShape = Literal['sphere']


type AdvantageStatus = Literal['None', 'Advantage', 'Disadvantage']


type SafePathItem = int


type ContactPosition = int


class AvailableWorldInteraction(TypedDict):
    subject_uuid: str
    behavior_id: str
    label: str
    description: NotRequired[str]
    default_priority: NotRequired[int]
    contact_positions: NotRequired[list[list[ContactPosition]]]
    connector_uuid: NotRequired[str | None]
    template_name: NotRequired[str | None]
    configured_action_ref: NotRequired[ContentRef | None]
    variant_facets: NotRequired[list[ActionVariantFacet]]
    reason: NotRequired[str | None]


class BaseCost(TypedDict):
    name: NotRequired[str]
    cost_type: Literal[
        'actions',
        'bonus_actions',
        'reactions',
        'movement',
        'spell_slot_1',
        'spell_slot_2',
        'spell_slot_3',
        'spell_slot_4',
        'spell_slot_5',
        'spell_slot_6',
        'spell_slot_7',
        'spell_slot_8',
        'spell_slot_9',
    ]
    cost: int
    resource_name: NotRequired[str | None]
    resource_cost: NotRequired[int]


type ConnectorDestinationStatus = Literal['known_clear', 'known_blocked', 'unknown']


class DamageRollProfile(TypedDict):
    dice_count: int
    die_size: int
    flat_bonus: NotRequired[int]
    damage_type: str
    save_dc: NotRequired[int | None]
    save_ability: NotRequired[str | None]
    double_on_critical: NotRequired[bool]


class EntityDestinationSelection(TypedDict):
    kind: NotRequired[Literal['entity_destination']]


class InformationEffectProfile(TypedDict):
    operation: ActionInformationOperation
    certainty: ActionWorldEffectCertainty
    anchor: ActionWorldEffectAnchor
    scope: ActionWorldEffectScope
    shape: NotRequired[ActionWorldEffectShape | None]
    radius_feet: NotRequired[int | None]
    sense_type: NotRequired[str | None]


class OpportunityAttackExposure(TypedDict):
    reactor_uuid: str
    reactor_name: str
    from_position: list[FromPositionItem]
    to_position: list[ToPositionItem]


type OutcomeApplicationScope = Literal['allocated_targets', 'each_affected_entity']


type OutcomeResolution = Literal['automatic', 'attack_roll', 'saving_throw', 'unknown']


class PositionPathSelection(TypedDict):
    kind: NotRequired[Literal['path']]
    max_length_feet: float
    max_segments: NotRequired[int]
    allow_origin_start: NotRequired[bool]
    origin_start_offset_cells: NotRequired[int]


class SinglePositionSelection(TypedDict):
    kind: NotRequired[Literal['single']]


type TargetEffectDisposition = Literal['beneficial', 'harmful', 'neutral']


type TargetType = Literal[
    'self',
    'entity',
    'creature_or_object',
    'position',
    'position_path',
    'position_los',
    'position_aoe',
    'multi_entity',
    'object',
]


class TopologyEffectProfile(TypedDict):
    operation: ActionTopologyOperation
    certainty: ActionWorldEffectCertainty
    anchor: ActionWorldEffectAnchor
    scope: ActionWorldEffectScope
    shape: NotRequired[ActionWorldEffectShape | None]
    radius_feet: NotRequired[int | None]
    affects_movement: NotRequired[bool]
    affects_vision: NotRequired[bool]
    affects_hazards: NotRequired[bool]


type DestinationPositionItem = int


class TraversalConnectorCommand(TypedDict):
    connector_uuid: str
    connector_revision: int
    connector_digest: str
    source_position: list[SourcePositionItem]
    destination_position: list[DestinationPositionItem]


type ExtraTargetPosition = int


class ActionSelection(TypedDict):
    action_index: int
    target_indices: list[int]
    extra_target_positions: NotRequired[list[list[ExtraTargetPosition]]]


class PreviewRequest(TypedDict):
    actor_uuid: str
    state_revision: str
    discovery_generation: int
    correlation_id: str
    selection: ActionSelection


type NextPosition = int


type PathItem12Item = int


type PathItem12 = list[PathItem12Item]


type AffordableEndpointItem = int


class SelectedRoute(TypedDict):
    path: list[PathItem12]
    cost_feet: float
    affordable_endpoint: list[AffordableEndpointItem]
    policy: Literal['normal', 'safe']
    opportunity_attack_exposures: list[OpportunityAttackExposure]
    is_hazardous: bool


type BodyPart = Literal[
    'Head', 'Body', 'Hands', 'Legs', 'Feet', 'Amulet', 'Ring', 'Cloak', 'Backpack'
]


class EndTurnIntent(TypedDict):
    kind: NotRequired[Literal['end_turn']]


class ExecuteSelectionIntent(TypedDict):
    kind: NotRequired[Literal['execute_selection']]
    discovery_generation: int
    selection: ActionSelection


type RingSlot = Literal['Left Ring', 'Right Ring']


class ToggleHandler(TypedDict):
    handler_uuid: str
    enabled: bool


class ToggleHandlerIntent(TypedDict):
    kind: NotRequired[Literal['toggle_handler']]
    discovery_generation: int
    handler: ToggleHandler


class UnequipItem(TypedDict):
    slot: WeaponSlot | BodyPart | RingSlot


class CommittedReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['committed']]
    cursor: PlayerCursor


class ExpiredReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['expired']]


class IndeterminateReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['indeterminate']]
    incident_id: str


class PendingReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['pending']]


class RejectedReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['rejected']]
    reason: Literal[
        'stale_state',
        'stale_discovery',
        'not_your_turn',
        'actor_unavailable',
        'invalid_selection',
        'unavailable_action',
        'invalid_item',
        'invalid_slot',
        'invalid_handler',
    ]


class UnknownReceipt(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    command_number: int
    kind: NotRequired[Literal['unknown']]


class ReceiptResponse(TypedDict):
    kind: NotRequired[Literal['receipt']]
    receipt: (
        PendingReceipt
        | CommittedReceipt
        | RejectedReceipt
        | IndeterminateReceipt
        | ExpiredReceipt
        | UnknownReceipt
    )


class StreamReady(TypedDict):
    kind: NotRequired[Literal['ready']]
    protocol: ProtocolIdentity
    after: PlayerCursor
    head: PlayerCursor
    status: StatusSnapshot


class StreamStatus(TypedDict):
    kind: NotRequired[Literal['stream_status']]
    status: StatusSnapshot


class ErrorAttachmentConflict(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['attachment_conflict']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorAttachmentReplaced(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['attachment_replaced']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorAudienceMismatch(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['audience_mismatch']]
    http_status: NotRequired[Literal[403]]
    retryable: NotRequired[Literal[False]]


class ErrorBusy(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['busy']]
    http_status: NotRequired[Literal[429]]
    retryable: NotRequired[Literal[True]]
    retry_after_ms: NotRequired[int]


class ErrorCatchUpRequired(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['catch_up_required']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]
    required_cursor: PlayerCursor


class ErrorCommandConflict(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['command_conflict']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorCommandNumber(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['command_number']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorEpochMismatch(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['epoch_mismatch']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorForbidden(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['forbidden']]
    http_status: NotRequired[Literal[403]]
    retryable: NotRequired[Literal[False]]


class ErrorGameClosed(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['game_closed']]
    http_status: NotRequired[Literal[410]]
    retryable: NotRequired[Literal[False]]


class ErrorGameFailed(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['game_failed']]
    http_status: NotRequired[Literal[503]]
    retryable: NotRequired[Literal[False]]


class ErrorGameNotFound(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['game_not_found']]
    http_status: NotRequired[Literal[404]]
    retryable: NotRequired[Literal[False]]


class ErrorGameTerminal(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['game_terminal']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorInternalFailure(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['internal_failure']]
    http_status: NotRequired[Literal[500]]
    retryable: NotRequired[Literal[False]]


class ErrorInvalidCursor(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['invalid_cursor']]
    http_status: NotRequired[Literal[400]]
    retryable: NotRequired[Literal[False]]


class ErrorInvalidRequest(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['invalid_request']]
    http_status: NotRequired[Literal[400]]
    retryable: NotRequired[Literal[False]]


class ErrorNotYourTurn(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['not_your_turn']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorProtocolMismatch(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['protocol_mismatch']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorQuerySuperseded(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['query_superseded']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorRecordingCapacity(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['recording_capacity']]
    http_status: NotRequired[Literal[503]]
    retryable: NotRequired[Literal[True]]
    retry_after_ms: NotRequired[int]


class ErrorRequestTooLarge(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['request_too_large']]
    http_status: NotRequired[Literal[413]]
    retryable: NotRequired[Literal[False]]


class ErrorResponseTooLarge(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['response_too_large']]
    http_status: NotRequired[Literal[500]]
    retryable: NotRequired[Literal[False]]


class ErrorResumeUnavailable(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['resume_unavailable']]
    http_status: NotRequired[Literal[410]]
    retryable: NotRequired[Literal[False]]
    earliest_cursor: PlayerCursor | None


class ErrorStaleDiscovery(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['stale_discovery']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorStaleState(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['stale_state']]
    http_status: NotRequired[Literal[409]]
    retryable: NotRequired[Literal[False]]


class ErrorStarting(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['starting']]
    http_status: NotRequired[Literal[503]]
    retryable: NotRequired[Literal[True]]
    retry_after_ms: NotRequired[int]


class ErrorUnauthenticated(TypedDict):
    kind: NotRequired[Literal['error']]
    incident_id: NotRequired[str | None]
    code: NotRequired[Literal['unauthenticated']]
    http_status: NotRequired[Literal[401]]
    retryable: NotRequired[Literal[False]]


type ApiError = ErrorInvalidRequest | ErrorUnauthenticated | ErrorForbidden | ErrorGameNotFound | ErrorEpochMismatch | ErrorAudienceMismatch | ErrorAttachmentReplaced | ErrorAttachmentConflict | ErrorCommandConflict | ErrorCommandNumber | ErrorStaleState | ErrorStaleDiscovery | ErrorNotYourTurn | ErrorCatchUpRequired | ErrorQuerySuperseded | ErrorInvalidCursor | ErrorResumeUnavailable | ErrorProtocolMismatch | ErrorRequestTooLarge | ErrorResponseTooLarge | ErrorBusy | ErrorStarting | ErrorRecordingCapacity | ErrorGameTerminal | ErrorGameFailed | ErrorGameClosed | ErrorInternalFailure


class ActionCancellation(TypedDict):
    phase: EventPhase | None
    action_economy_spent: bool
    outcome_code: str | None


class ActionFact(TypedDict):
    kind: NotRequired[Literal['action']]
    source_entity_uuid: str
    target_entity_uuid: str | None
    behavior_id: str | None
    name: str | None
    source_item_uuid: NotRequired[str | None]
    reaction: NotRequired[ActionReaction | None]
    font_conversion: NotRequired[FontConversion | None]


class AppliedClassLevel(TypedDict):
    step_id: str
    character_level: int
    class_id: CharacterClass
    resulting_class_level: int
    subclass_id: NotRequired[CharacterSubclass | None]
    choices: NotRequired[list[ClassChoiceSelection]]


class AppliedOriginState(TypedDict):
    base_ability_scores: NotRequired[
        list[
            list[
                Literal[
                    'strength',
                    'dexterity',
                    'constitution',
                    'intelligence',
                    'wisdom',
                    'charisma',
                ]
                | BaseAbilityScore
            ]
        ]
    ]
    flexible_ability_bonuses: NotRequired[
        list[
            list[
                Literal[
                    'strength',
                    'dexterity',
                    'constitution',
                    'intelligence',
                    'wisdom',
                    'charisma',
                ]
                | FlexibleAbilityBonus
            ]
        ]
    ]
    choices: NotRequired[list[OriginChoiceSelection]]


class BodyReleaseRegion(TypedDict):
    ellipse: ResidueEllipse
    positions: list[list[Position]]
    elevation_steps: int


class BodyReleaseResult(TypedDict):
    release_id: str
    position: list[PositionItem]
    occupancy_layer: OccupancyLayer
    deposited_position: NotRequired[list[DepositedPositionItem] | None]
    pattern: NotRequired[Literal['piercing', 'slashing', 'blunt'] | None]
    critical_hit: NotRequired[bool]
    regions: NotRequired[list[BodyReleaseRegion]]
    primary_damage_type: NotRequired[DamageType | None]
    secondary_damage_type: NotRequired[DamageType | None]


class BoundaryStructure(TypedDict):
    structure: BoundaryStructureKind
    material: Material
    blocked_channels: list[WorldEdgeChannel]
    contact_passage: NotRequired[ContactPassage]


class ConditionDurationSummary(TypedDict):
    duration_type: DurationType
    remaining_rounds: int | None


class ConditionState(TypedDict):
    duration: NotRequired[ConditionDurationSummary | None]
    condition_uuid: str
    name: str
    category: ConditionCategory
    semantic_key: str
    behavior_id: NotRequired[str | None]
    tags: list[ConditionTag]
    removal_triggers: list[ConditionRemovalTrigger]
    agency_denial: ConditionAgencyDenial
    outcome_protections: list[OutcomeProtection]
    applied_source_event_cursor: NotRequired[int | None]
    suppression_provider_uuids: NotRequired[list[str]]
    duplicate_count: NotRequired[int | None]
    size_change: NotRequired[Literal['enlarge', 'reduce'] | None]
    energy_type: NotRequired[DamageType | None]
    metamagic_mode: NotRequired[Literal['quickened', 'twinned', 'distant'] | None]
    affected_item_uuid: NotRequired[str | None]
    enhanced_ability: NotRequired[
        Literal[
            'strength',
            'dexterity',
            'constitution',
            'intelligence',
            'wisdom',
            'charisma',
        ]
        | None
    ]
    concentration_slots: NotRequired[list[ItemConcentrationSlot]]


class ConnectorMovementLogData(TypedDict):
    entity_name: str
    entity_uuid: str
    start_position: list[StartPositionItem]
    end_position: list[EndPositionItem]
    path: NotRequired[list[list[PathItem]]]
    distance_feet: NotRequired[int]
    movement_cost: NotRequired[int]
    requested_end_position: NotRequired[list[RequestedEndPositionItem] | None]
    termination_reason: NotRequired[str]
    controller_revalidation: NotRequired[bool]
    controller_revalidation_reason: NotRequired[str | None]
    kind: NotRequired[Literal['connector_movement']]
    movement_type: NotRequired[Literal['connector']]
    objective_end_position: list[ObjectiveEndPositionItem]
    start_elevation_feet: int
    requested_end_elevation_feet: int
    end_elevation_feet: int
    connector_uuid: str
    connector_authored_id: str
    connector_kind: TraversalConnectorKind
    connector_presentation_key: str
    connector_provocation_policy: ConnectorProvocationPolicy


class ContentAttribution(TypedDict):
    role: Literal['behavior', 'source_item', 'effective_handler']
    behavior_id: str
    provided_by_id: NotRequired[str | None]
    origin_root_id: NotRequired[str | None]
    source_entity_uuid: NotRequired[str | None]
    triggering_event_uuid: NotRequired[str | None]
    triggering_lineage_uuid: NotRequired[str | None]
    emitted_lineage_uuids: NotRequired[list[str]]
    handler_name: NotRequired[str | None]
    dispatch_index: NotRequired[int | None]
    outcome: NotRequired[HandlerDispatchOutcome | None]


class CreationWitness(TypedDict):
    birth_event_uuid: str
    manifestation: SummonManifestation


class DamageRequestFact(TypedDict):
    kind: NotRequired[Literal['damage']]
    stage: NotRequired[Literal['taken']]
    source_entity_uuid: str | None
    target_entity_uuid: str
    intercepted_by_condition_uuid: NotRequired[str | None]
    source_condition_uuid: NotRequired[str | None]
    relentless_rage: NotRequired[RelentlessRageIntervention | None]


class DamageResultFact(TypedDict):
    kind: NotRequired[Literal['damage']]
    stage: NotRequired[Literal['applied']]
    source_entity_uuid: str | None
    target_entity_uuid: str
    applied_damage: int
    resulting_normal_hp: int
    resulting_temporary_hp: int
    damage_type: DamageType
    body_release: NotRequired[BodyReleaseResult | None]
    effect_id: NotRequired[str | None]
    spatial_source: NotRequired[SpatialDamageSource | None]
    source_condition_uuid: NotRequired[str | None]


class DamageRollDisplay(TypedDict):
    dice_str: str
    dice_results: NotRequired[list[int]]
    bonus: NotRequired[int]
    total: int
    damage_type: str
    bonus_breakdown: NotRequired[list[ModifierBreakdown]]


class EntityStatsState(TypedDict):
    normal_hp: int
    maximum_hp: int
    temporary_hp: int
    temporary_hp_grant: NotRequired[TemporaryHitPointsGrant | None]
    armor_class: int
    healing_blocked: bool
    damage_affinities: list[list[str]]
    resolved_size: NotRequired[Size | None]
    native_plane_id: NotRequired[str]
    current_plane_id: NotRequired[str]
    spatial_disposition: NotRequired[SpatialDisposition]


class EquipmentSpritePresentation(TypedDict):
    equipment_slot: VisualLoadoutSlot
    render_layer: EquipmentRenderLayer
    sprite_key: str
    tint_rgb: int


class ForcedMovementFact(TypedDict):
    kind: NotRequired[Literal['forced_movement']]
    source_entity_uuid: str | None
    target_entity_uuid: str
    start_position: list[StartPositionItem]
    end_position: list[EndPositionItem]
    actual_distance: int
    disclosed_path: NotRequired[list[list[DisclosedPathItem]]]
    start_elevation_feet: NotRequired[int | None]
    end_elevation_feet: NotRequired[int | None]
    drop_feet: NotRequired[int]
    landing_kind: NotRequired[LandingKind]


class ItemChargeFact(TypedDict):
    kind: NotRequired[Literal['item_charge']]
    source_entity_uuid: str
    item_uuid: str
    charges_after: int
    stack_count_after: int
    item_destroyed: bool
    resource_change: NotRequired[ItemResourceChange | None]


class ItemEffectPresentationState(TypedDict):
    duration: NotRequired[ConditionDurationSummary | None]
    effect_uuid: str
    contribution_uuid: NotRequired[str | None]
    behavior_id: str
    display_name: NotRequired[str]
    description: NotRequired[str]
    damage_type: NotRequired[DamageType | None]
    applied_source_event_cursor: NotRequired[int | None]
    suppression_provider_uuids: NotRequired[list[str]]


class ItemRemnantState(TypedDict):
    door_open: NotRequired[bool | None]
    door_swing: NotRequired[DoorSwing | None]
    mechanism_state: NotRequired[TrapState | None]
    intact_supported_items: NotRequired[list[str]]


class LifeFact(TypedDict):
    kind: NotRequired[Literal['life']]
    entity_uuid: str
    previous_state: LifeState
    new_state: LifeState
    reason: LifeStateChangeReason
    normal_hit_points: int
    remains_disposition: NotRequired[RemainsDisposition]
    preserved_equipped_item_uuids: NotRequired[list[str]]


class MovementFact(TypedDict):
    kind: NotRequired[Literal['movement']]
    source_entity_uuid: str
    trajectory: MovementTrajectory
    start_position: NotRequired[list[StartPositionItem] | None]
    end_position: NotRequired[list[EndPositionItem] | None]
    requested_end_position: NotRequired[list[RequestedEndPositionItem] | None]
    path: NotRequired[list[list[PathItem]]]
    start_elevation_feet: NotRequired[int | None]
    end_elevation_feet: NotRequired[int | None]
    movement_mode: NotRequired[MovementMode | None]
    start_layer: NotRequired[OccupancyLayer | None]
    end_layer: NotRequired[OccupancyLayer | None]
    connector_presentation_key: NotRequired[str | None]


class PerceivedContact(TypedDict):
    position: list[PositionItem]
    visual: bool
    special_senses: NotRequired[list[SensesType]]


class PlayerCharacterSheet(TypedDict):
    actor_uuid: str
    species: Species | None
    species_variant: SpeciesVariant | None
    background: Background | None
    origin: AppliedOriginState | None
    class_levels: list[AppliedClassLevel]
    abilities: list[
        list[
            Literal[
                'strength',
                'dexterity',
                'constitution',
                'intelligence',
                'wisdom',
                'charisma',
            ]
            | Ability
        ]
    ]
    skills: list[str]
    expertise: list[str]
    saves: list[str]
    proficiency_bonus: int
    resources: list[PlayerResource]
    name: NotRequired[str]
    portrait_key: NotRequired[str | None]
    normal_hp: NotRequired[int]
    maximum_hp: NotRequired[int]
    compatible_item_slots: NotRequired[list[list[str | list[str]]]]
    handler_details: NotRequired[list[AvailableHandlerInfo]]


class PlayerHUDSnapshot(TypedDict):
    generation: str
    observer_uuid: str
    revision: int
    initiative: list[str]
    sheets: list[PlayerCharacterSheet]


class ResidueContribution(TypedDict):
    ellipses: list[ResidueEllipse]
    amount: NotRequired[int]
    deposit_source: NotRequired[MaterialDepositSource | None]


class RollModificationLogData(TypedDict):
    kind: NotRequired[Literal['roll_modification']]
    roll_type: str
    modifications: list[RollModificationLogFact]


class SenseMode(TypedDict):
    sense_type: SensesType
    range_feet: NotRequired[int]


class SpatialChangeLogData(TypedDict):
    kind: NotRequired[Literal['spatial_change']]
    operation: SpatialEffectChangeOperation
    content_identity: str
    layer: SpatialEffectLayer
    affected_positions: list[list[AffectedPosition]]


class SpatialEffectStateFact(TypedDict):
    kind: NotRequired[Literal['spatial_effect_state']]
    spatial_effect_uuid: str
    positions: list[list[Position]]
    previous_state: TrapState | None
    state: TrapState | None
    previous_pressed: NotRequired[bool | None]
    pressed: NotRequired[bool | None]
    operation: NotRequired[SpatialEffectChangeOperation]
    interaction_operation: NotRequired[SpatialEffectInteractionOperation | None]
    removed_positions: NotRequired[list[list[RemovedPosition]]]


class SpatialFact(TypedDict):
    kind: NotRequired[Literal['spatial']]
    change_type: SpatialChangeType
    entity_uuid: str | None
    position: list[PositionItem]
    object_uuid: NotRequired[str | None]
    commit_event_uuid: NotRequired[str | None]
    previous_occupancy_layer: NotRequired[OccupancyLayer | None]
    occupancy_layer: NotRequired[OccupancyLayer | None]
    terminal_departure: NotRequired[bool]
    terminal_cause: NotRequired[SummonDepartureCause | None]
    creation: NotRequired[CreationWitness | None]


class SpellSaveLogData(TypedDict):
    kind: NotRequired[Literal['spell_save']]
    caster_name: str
    caster_uuid: str
    target_name: str
    target_uuid: str
    spell_name: str
    spell_level: NotRequired[int]
    save_ability: str
    save_dc: int
    save_roll: DiceRollDisplay
    save_bonus_breakdown: NotRequired[list[ModifierBreakdown]]
    save_advantage_breakdown: NotRequired[list[ModifierBreakdown]]
    save_success: bool
    damage_rolls: NotRequired[list[DamageRollDisplay]]
    base_damage: NotRequired[int]
    final_damage: NotRequired[int]
    damage_type: NotRequired[str]
    target_hp_after: NotRequired[int | None]


class TemporaryHitPointsFact(TypedDict):
    kind: NotRequired[Literal['temporary_hit_points']]
    entity_uuid: str
    resulting_temporary_hp: int
    grant: NotRequired[TemporaryHitPointsGrant | None]


class TileResidueState(TypedDict):
    condition_uuid: str
    residue_id: str
    description: str
    amount: NotRequired[int]
    max_amount: NotRequired[int]
    contributions: NotRequired[list[ResidueContribution]]


class VisualItem(TypedDict):
    slot: str
    item_uuid: str
    item_id: str
    item_kind: ItemPresentationKind
    visual_item_name: str
    visual_variant_id: str | None
    equipped_visual_policy: EquippedVisualPolicy
    item_effects: NotRequired[list[ItemEffectPresentationState]]
    suppression_provider_uuids: NotRequired[list[str]]


class VisualLoadout(TypedDict):
    active_weapon_set: WeaponSet
    layers: list[VisualItem]


class WallAssemblyPresentationGeometry(TypedDict):
    shape: NotRequired[Literal['wall_assembly']]
    removed_sections: NotRequired[list[ObjectSectionVolume]]
    path: WallSegment | WallRing | WallPolyline | WallDome
    base_height_steps: int
    width_feet: float
    height_feet: float


class WallPresentationGeometry(TypedDict):
    shape: NotRequired[Literal['wall']]
    path: WallSegment | WallRing
    base_height_steps: int
    width_feet: float
    height_feet: float
    hot_side: NotRequired[Literal['left', 'right', 'inside', 'outside'] | None]


class WorldObjectPlacement(TypedDict):
    object_uuid: str
    tile_uuid: str
    position: list[PositionItem]
    kind: WorldPlacementKind
    occupies_bands: bool
    boundary_direction: NotRequired[CardinalDirection | None]
    base_height_steps: int
    top_height_steps: int
    orientation: NotRequired[CardinalDirection | None]
    covered_supports: NotRequired[list[WorldObjectSupport]]
    removed_bands: NotRequired[list[list[RemovedBand]]]


class WorldTileState(TypedDict):
    tile_uuid: str
    position: list[PositionItem]
    surface: TileSurface
    name: str
    blocks_optics: bool
    blocks_propagation: bool
    walking_cost: int
    flying_cost: int
    swimming_cost: int
    burrowing_cost: int
    elevation_steps: int
    surface_kind: ElevationSurfaceKind
    slope_axis: NotRequired[SlopeAxis | None]
    default_light: LightLevel
    resolved_light: LightLevel
    condition_names: NotRequired[list[str]]
    residues: NotRequired[list[TileResidueState]]


class ActionOutcomeProfile(TypedDict):
    effect_id: NotRequired[str | None]
    resolution: OutcomeResolution
    applications: NotRequired[int]
    application_scope: NotRequired[OutcomeApplicationScope]
    damage_rolls: NotRequired[list[DamageRollProfile]]
    attack_bonus: NotRequired[int | None]
    advantage: NotRequired[AdvantageStatus]
    critical_threshold: NotRequired[int]
    critical_extra_dice: NotRequired[int]
    save_dc: NotRequired[int | None]
    save_ability: NotRequired[str | None]
    half_damage_on_save: NotRequired[bool]
    scope: NotRequired[Literal['actor_baseline']]


class ActionSetupMaintenanceProfile(TypedDict):
    trigger: ActionSetupMaintenanceTrigger
    skill_name: str
    initial_dc: int
    dc_increment_per_success: NotRequired[int]
    check_bonus: int
    check_advantage: NotRequired[AdvantageStatus]
    failure: ActionSetupMaintenanceFailure


class ActionTargetEffectBranchProfile(TypedDict):
    effect_id: str
    disposition: TargetEffectDisposition
    included_creature_types: NotRequired[list[str]]
    excluded_creature_types: NotRequired[list[str]]
    resolution: OutcomeResolution
    save_dc: NotRequired[int | None]
    save_ability: NotRequired[str | None]
    condition_fact_ids: NotRequired[list[str]]
    condition_semantic_keys: NotRequired[list[str]]


class ActionTargetEffectProfile(TypedDict):
    semantic_id: str
    branches: list[ActionTargetEffectBranchProfile]


class ActionWorldEffectProfile(TypedDict):
    semantic_id: str
    information_effects: NotRequired[list[InformationEffectProfile]]
    topology_effects: NotRequired[list[TopologyEffectProfile]]


class AvailableTarget(TypedDict):
    target_kind: NotRequired[Literal['creature', 'object']]
    index: int
    target_uuid: NotRequired[str | None]
    position: NotRequired[list[PositionItem] | None]
    target_name: NotRequired[str | None]
    distance: NotRequired[int | None]
    path_cost: NotRequired[int | None]
    extra_target_uuids: NotRequired[list[str] | None]
    secondary_targets: NotRequired[list[AvailableTarget] | None]
    is_path_hazardous: NotRequired[bool]
    safe_path_cost: NotRequired[int | None]
    path: NotRequired[list[list[PathItem]] | None]
    safe_path: NotRequired[list[list[SafePathItem]] | None]
    opportunity_attack_exposures: NotRequired[list[OpportunityAttackExposure]]
    safe_path_opportunity_attack_exposures: NotRequired[list[OpportunityAttackExposure]]
    affected_entity_uuids: NotRequired[list[str] | None]
    affected_entity_names: NotRequired[list[str] | None]
    affected_count: NotRequired[int | None]
    affected_positions: NotRequired[list[list[AffectedPosition]] | None]


class ConnectorTraversalDiscovery(TypedDict):
    command: TraversalConnectorCommand
    authored_id: str
    kind: TraversalConnectorKind
    presentation_key: str
    source_elevation_feet: int
    destination_elevation_feet: int
    movement_cost_feet: int
    action_cost_type: NotRequired[ConnectorActionCostType | None]
    action_cost_amount: NotRequired[int]
    bidirectional: bool
    provocation_policy: ConnectorProvocationPolicy
    destination_status: ConnectorDestinationStatus


class AvailableSelectionPreview(TypedDict):
    can_confirm: bool
    reason: NotRequired[str | None]
    effective_target_uuids: NotRequired[list[str]]
    next_targets: NotRequired[list[AvailableTarget]]
    next_positions: NotRequired[list[list[NextPosition]]]
    geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    affected_positions: NotRequired[list[list[AffectedPosition]]]
    selected_route: NotRequired[SelectedRoute | None]


class PreviewResponse(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    kind: NotRequired[Literal['preview']]
    state_revision: str
    request: PreviewRequest
    preview: AvailableSelectionPreview


class EquipItem(TypedDict):
    item_uuid: str
    slot: WeaponSlot | BodyPart | RingSlot


class UnequipIntent(TypedDict):
    kind: NotRequired[Literal['unequip']]
    item: UnequipItem


class AttackFact(TypedDict):
    kind: NotRequired[Literal['attack']]
    source_entity_uuid: str
    target_entity_uuid: str
    behavior_id: str | None
    name: str | None
    weapon_slot: WeaponSlot
    attack_outcome: AttackOutcome | None
    damage_types: list[DamageType]
    source_item_id: str | None
    source_item_uuid: NotRequired[str | None]
    item_effects: NotRequired[list[ItemEffectPresentationState]]
    intercepted_by_condition_uuid: NotRequired[str | None]
    projectile_deflection_position: NotRequired[list[float] | None]
    target_kind: NotRequired[Literal['creature', 'object']]
    target_position: NotRequired[list[TargetPositionItem] | None]
    target_base_height_steps: NotRequired[int | None]
    attack_source_kind: NotRequired[Literal['equipped', 'unarmed', 'natural']]


class AttackLogData(TypedDict):
    kind: NotRequired[Literal['attack']]
    attacker_name: str
    attacker_uuid: str
    target_name: str
    target_uuid: str
    weapon_name: str
    weapon_slot: NotRequired[str | None]
    attack_roll: DiceRollDisplay
    attack_breakdown: NotRequired[list[ModifierBreakdown]]
    target_ac: int
    ac_breakdown: NotRequired[list[ModifierBreakdown]]
    outcome: str
    is_hit: bool
    is_crit: bool
    damage_rolls: NotRequired[list[DamageRollDisplay]]
    total_damage: NotRequired[int]
    target_hp: NotRequired[int | None]
    advantage_breakdown: NotRequired[list[ModifierBreakdown]]
    is_opportunity_attack: NotRequired[bool]
    is_long_range: NotRequired[bool]
    is_threatened: NotRequired[bool]


class CombatLogEntry(TypedDict):
    entry_type: CombatLogEntryType
    source_name: str
    source_uuid: str
    target_name: NotRequired[str | None]
    target_uuid: NotRequired[str | None]
    compact: str
    verbose: str
    detailed: str
    data: (
        AttackLogData
        | MovementLogData
        | JumpMovementLogData
        | ConnectorMovementLogData
        | SavingThrowLogData
        | SpellSaveLogData
        | SpellInterruptionLogData
        | SkillCheckLogData
        | EntitySpottedLogData
        | HazardDetectedLogData
        | DamageTakenLogData
        | HealLogData
        | ActionLogData
        | TurnLogData
        | MultiEntityLogData
        | RollModificationLogData
        | EmptyLogData
        | ConditionRemovedLogData
        | DeathLogData
        | SpellDamageLogData
        | DeathSaveLogData
        | ShoveLogData
        | StepMovementLogData
        | ForcedMovementLogData
        | ObservedMovementLogData
        | UnlocatedMovementLogData
        | UnknownMovementLogData
        | SpatialChangeLogData
        | SpatialInteractionLogData
    )
    success: NotRequired[bool | None]
    sub_entries: NotRequired[list[CombatLogEntry]]


class ContentPresentation(TypedDict):
    icon_key: NotRequired[str | None]
    portrait_key: NotRequired[str | None]
    sprite_key: NotRequired[str | None]
    visual_variant_key: NotRequired[str | None]
    tint_rgb: NotRequired[int | None]
    vfx_profile: NotRequired[str | None]
    audio_key: NotRequired[str | None]
    ui_group: NotRequired[str | None]
    equipment_sprites: NotRequired[list[EquipmentSpritePresentation]]


class SpellSuppression(TypedDict):
    antimagic: NotRequired[bool]
    provider_uuid: str
    positions: list[list[Position]]
    provider_content_ref: NotRequired[ContentRef | None]
    area_geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    anchor_elevation_steps: NotRequired[int | None]


class ActionSelfSetupProfile(TypedDict):
    semantic_id: str
    duration: ActionSetupDuration
    maximum_duration_rounds: NotRequired[int | None]
    condition_fact_ids: NotRequired[list[str]]
    active_condition_semantic_keys: NotRequired[list[str]]
    increases_weapon_damage: NotRequired[bool]
    resistance_damage_types: NotRequired[list[str]]
    grants_bonus_action_attack: NotRequired[bool]
    grants_outgoing_attack_advantage: NotRequired[bool]
    grants_incoming_attack_advantage: NotRequired[bool]
    grants_incoming_attack_disadvantage: NotRequired[bool]
    armor_class_bonus: NotRequired[int]
    movement_speed_multiplier: NotRequired[float]
    extra_actions_per_turn: NotRequired[int]
    grants_invisibility: NotRequired[bool]
    incapacitates_on_removal: NotRequired[bool]
    maintenance: NotRequired[ActionSetupMaintenanceProfile | None]


class AvailableActionInfo(TypedDict):
    discovery_generation: NotRequired[int]
    discovery_index: NotRequired[int]
    discovery_runtime: NotRequired[str | None]
    discovery_actor_uuid: NotRequired[str | None]
    template_name: str
    semantic_key: NotRequired[str]
    behavior_id: str
    provided_by_id: str
    origin_root_id: NotRequired[str | None]
    configured_action_ref: NotRequired[ContentRef | None]
    target_type: TargetType
    position_selection: NotRequired[
        SinglePositionSelection
        | PositionPathSelection
        | EntityDestinationSelection
        | None
    ]
    availability_status: ActionAvailabilityStatus
    valid_targets: NotRequired[list[AvailableTarget]]
    can_afford: bool
    display_name: str
    description: NotRequired[str]
    cost_type: Literal[
        'actions',
        'bonus_actions',
        'reactions',
        'movement',
        'spell_slot_1',
        'spell_slot_2',
        'spell_slot_3',
        'spell_slot_4',
        'spell_slot_5',
        'spell_slot_6',
        'spell_slot_7',
        'spell_slot_8',
        'spell_slot_9',
    ]
    cost_amount: NotRequired[int]
    restricted_action_budget: NotRequired[str | None]
    costs: NotRequired[list[BaseCost]]
    weapon_slot: NotRequired[str | None]
    weapon_name: NotRequired[str | None]
    damage_types: NotRequired[list[str]]
    outcome_profile: NotRequired[ActionOutcomeProfile | None]
    self_setup_profile: NotRequired[ActionSelfSetupProfile | None]
    target_effect_profile: NotRequired[ActionTargetEffectProfile | None]
    world_effect_profile: NotRequired[ActionWorldEffectProfile | None]
    performs_attack: NotRequired[bool]
    action_category: NotRequired[ActionCategory]
    base_template_name: NotRequired[str | None]
    spell_level: NotRequired[int | None]
    cast_at_level: NotRequired[int | None]
    is_spell_variant: NotRequired[bool]
    requires_concentration: NotRequired[bool]
    num_projectiles: NotRequired[int | None]
    allow_same_target: NotRequired[bool | None]
    is_item_use: NotRequired[bool]
    source_item_uuid: NotRequired[str | None]
    item_stack_count: NotRequired[int | None]
    item_charge_cost: NotRequired[int]
    fixed_healing: NotRequired[int | None]
    allocation_completion: NotRequired[Literal['selected_only', 'fill_primary']]
    variant_facets: NotRequired[list[ActionVariantFacet]]
    interaction_affordance: NotRequired[ActionAffordance]
    connector_traversal: NotRequired[ConnectorTraversalDiscovery | None]


class AvailableActionsResult(TypedDict):
    discovery_generation: NotRequired[int]
    entity_uuid: str
    entity_actions: NotRequired[list[AvailableActionInfo]]
    position_actions: NotRequired[list[AvailableActionInfo]]
    self_actions: NotRequired[list[AvailableActionInfo]]
    object_actions: NotRequired[list[AvailableActionInfo]]
    remaining_movement: NotRequired[int]
    world_interactions: NotRequired[list[AvailableWorldInteraction]]
    handler_details: NotRequired[list[AvailableHandlerInfo]]


class ChoicesResponse(TypedDict):
    game_id: str
    game_epoch: str
    audience_id: str
    kind: NotRequired[Literal['choices']]
    state_revision: str
    correlation_id: str
    force_attack: bool
    choices: AvailableActionsResult


class EquipIntent(TypedDict):
    kind: NotRequired[Literal['equip']]
    item: EquipItem


class CommandRequest(TypedDict):
    command_number: int
    actor_uuid: str
    state_revision: str
    intent: (
        ExecuteSelectionIntent
        | EndTurnIntent
        | EquipIntent
        | UnequipIntent
        | ToggleHandlerIntent
    )


class CombatLogAppend(TypedDict):
    generation: str
    observer_uuid: str
    encounter_log_index: int
    operation_end_cursor: int
    entry: CombatLogEntry


class ContentDescriptor(TypedDict):
    display_name: str
    description: NotRequired[str]
    tags: NotRequired[list[str]]
    visibility: ContentVisibility
    presentation: NotRequired[ContentPresentation]
    ordering: NotRequired[ContentOrdering]
    related_content_refs: NotRequired[list[ContentRef]]
    ref: ContentRef


class FloorItem(TypedDict):
    item_uuid: str
    item_id: str
    name: str
    visual_item_name: str
    visual_variant_id: str | None
    map_char: str
    boundary_structure: BoundaryStructure | None
    is_open: bool | None
    is_lit: bool | None
    stack_count: NotRequired[int]
    is_pickable: NotRequired[bool]
    item_effects: NotRequired[list[ItemEffectPresentationState]]
    suppression_provider_uuids: NotRequired[list[str]]
    blocks_propagation: NotRequired[bool]
    contact_passage: NotRequired[ContactPassage]
    supported_by_uuid: NotRequired[str | None]
    is_engaged: NotRequired[bool | None]
    surface_residues: NotRequired[list[ObjectResidueState]]
    current_hit_points: NotRequired[int | None]
    maximum_hit_points: NotRequired[int | None]
    concentration_capacity: NotRequired[int]
    concentration_slots: NotRequired[list[ItemConcentrationSlot]]
    door_mechanism: NotRequired[DoorMechanism | None]
    door_swing: NotRequired[DoorSwing | None]
    remnant_state: NotRequired[ItemRemnantState | None]
    integrity: NotRequired[ItemIntegrity]
    destruction_outcome: NotRequired[str | None]
    construction_owner_uuid: NotRequired[str | None]
    construction_geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    construction_suppressions: NotRequired[list[SpellSuppression]]
    known_to_creator: NotRequired[bool]


class ItemPresentationState(TypedDict):
    suppression_provider_uuids: NotRequired[list[str]]
    item_uuid: str
    item_id: str
    name: str
    description: NotRequired[str | None]
    item_kind: ItemPresentationKind
    rarity: ItemRarity
    weight: float
    value: NotRequired[int]
    tags: NotRequired[list[str]]
    is_pickable: NotRequired[bool]
    is_equippable: NotRequired[bool]
    is_usable: NotRequired[bool]
    is_targetable: NotRequired[bool]
    door_mechanism: NotRequired[DoorMechanism | None]
    door_swing: NotRequired[DoorSwing | None]
    remnant_state: NotRequired[ItemRemnantState | None]
    integrity: NotRequired[ItemIntegrity]
    destruction_outcome: NotRequired[str | None]
    stack_id: NotRequired[str | None]
    visual_item_name: str
    visual_variant_id: NotRequired[str | None]
    item_effects: NotRequired[list[ItemEffectPresentationState]]
    equipped_visual_policy: EquippedVisualPolicy
    damage_dice: NotRequired[str | None]
    damage_type: NotRequired[str | None]
    weapon_properties: NotRequired[list[str]]
    armor_type: NotRequired[str | None]
    armor_ac: NotRequired[int | None]
    shield_ac_bonus: NotRequired[int | None]
    charges: NotRequired[int | None]
    max_charges: NotRequired[int | None]
    stack_count: int
    max_stack: int
    is_consumable: bool
    map_char: NotRequired[str]
    include_in_senses_objects: NotRequired[bool]
    include_in_adjacent_senses_objects: NotRequired[bool]
    include_in_available_object_actions: NotRequired[bool]
    current_hit_points: NotRequired[int | None]
    maximum_hit_points: NotRequired[int | None]
    concentration_capacity: NotRequired[int]
    concentration_slots: NotRequired[list[ItemConcentrationSlot]]
    boundary_structure: NotRequired[BoundaryStructure | None]
    construction_owner_uuid: NotRequired[str | None]
    construction_geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    construction_suppressions: NotRequired[list[SpellSuppression]]
    known_to_creator: NotRequired[bool]
    supported_by_uuid: NotRequired[str | None]
    contact_passage: NotRequired[ContactPassage]
    surface_residues: NotRequired[list[ObjectResidueState]]
    linked_spatial_condition_uuid: NotRequired[str | None]
    is_open: NotRequired[bool | None]
    is_engaged: NotRequired[bool | None]
    blocks_movement: NotRequired[bool]
    blocks_optics: NotRequired[bool]
    blocks_propagation: NotRequired[bool]
    is_lit: NotRequired[bool | None]
    very_bright_radius_feet: NotRequired[int | None]
    bright_radius_feet: NotRequired[int | None]
    dim_radius_feet: NotRequired[int | None]


class ObjectDestroyedFact(TypedDict):
    kind: NotRequired[Literal['object_destroyed']]
    object_uuid: str
    replacement_uuid: NotRequired[str | None]
    placement: WorldObjectPlacement
    item_id: str
    remnant_state: NotRequired[ItemRemnantState | None]
    destruction_outcome: NotRequired[str | None]
    remains_disposition: NotRequired[RemainsDisposition]
    previous_item: NotRequired[FloorItem | None]
    affected_volume: NotRequired[ObjectSectionVolume | None]
    resulting_placement: NotRequired[WorldObjectPlacement | None]


class PerceivedSpatialEffect(TypedDict):
    duration: NotRequired[ConditionDurationSummary | None]
    content_ref: ContentRef
    name: str
    description: str
    positions: list[list[Position]]
    owner_revision: NotRequired[int | None]
    apparent_presence: NotRequired[bool]
    trap_state: NotRequired[TrapState | None]
    pressed: NotRequired[bool | None]
    direction: NotRequired[list[DirectionItem] | None]
    anchor_item_uuid: NotRequired[str | None]
    anchor_entity_uuid: NotRequired[str | None]
    energy_type: NotRequired[DamageType | None]
    presence_mode: NotRequired[Literal['awe', 'fear'] | None]
    sustainer_item_uuid: NotRequired[str | None]
    concentration_slot_uuid: NotRequired[str | None]
    anchor_position: NotRequired[list[AnchorPositionItem] | None]
    anchor_elevation_steps: NotRequired[int | None]
    area_geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    construction_sections: NotRequired[list[WallAssemblyPresentationGeometry]]
    area_propagation: NotRequired[Literal['line_of_effect', 'connected'] | None]
    deposit_source: NotRequired[MaterialDepositSource | None]
    visible_volume_positions: NotRequired[list[list[VisibleVolumePosition]]]
    upper_volume_surfaces: NotRequired[list[VolumeSurfaceSight]]
    suppressions: NotRequired[list[SpellSuppression]]


class PlayerObject(TypedDict):
    placement: WorldObjectPlacement
    item: FloorItem


class SensoryFact(TypedDict):
    kind: NotRequired[Literal['sensory']]
    observed_changes: NotRequired[list[ObservedChangeRef]]
    observer_uuid: str
    initial: bool
    observer_position: list[ObserverPositionItem]
    observer_position_changed: bool
    effective_light_levels_changed: dict[str, int]
    cause_event_uuid: str | None
    visible_cells_added: list[list[VisibleCellsAddedItem]]
    visible_cells_removed: list[list[VisibleCellsRemovedItem]]
    seen_cells_added: list[list[SeenCellsAddedItem]]
    entity_contacts_changed: dict[str, PerceivedContact]
    entity_contacts_removed: list[str]
    object_contacts_changed: dict[str, PerceivedContact]
    object_contacts_removed: list[str]
    sense_modes_changed: bool
    sense_modes: list[SenseMode] | None
    passive_perception_changed: bool
    passive_perception: int | None
    visual_access_changed: bool
    visual_access: int | None
    paths_dirty: bool
    hazardous_cells_changed: NotRequired[dict[str, bool]]
    spatial_effects_changed: NotRequired[dict[str, PerceivedSpatialEffect]]
    spatial_effects_removed: NotRequired[list[str]]


class SpellFact(TypedDict):
    kind: NotRequired[Literal['spell']]
    source_entity_uuid: str
    target_entity_uuid: str | None
    behavior_id: str | None
    name: str | None
    source_position: list[SourcePositionItem] | None
    declared_target_entity_uuids: list[str]
    application: ApplicationMembership | None
    propagation: NotRequired[EffectPropagationLink | None]
    attack_outcome: NotRequired[AttackOutcome | None]
    cast_origin: NotRequired[Literal['actor', 'source_item']]
    source_item_uuid: NotRequired[str | None]
    effect_id: NotRequired[str | None]
    aoe_position: NotRequired[list[AoePositionItem] | None]
    area_geometry: NotRequired[
        SpherePresentationGeometry
        | ConePresentationGeometry
        | LinePresentationGeometry
        | CubePresentationGeometry
        | CylinderPresentationGeometry
        | WallPresentationGeometry
        | WallAssemblyPresentationGeometry
        | None
    ]
    resolved_area_positions: NotRequired[list[list[ResolvedAreaPosition]] | None]
    suppressions: NotRequired[list[SpellSuppression]]
    area_propagation: NotRequired[Literal['line_of_effect', 'connected']]
    target_kind: NotRequired[Literal['creature', 'object']]
    target_position: NotRequired[list[TargetPositionItem] | None]
    target_base_height_steps: NotRequired[int | None]


class WorldUpdate(TypedDict):
    event_uuid: str
    tiles: list[WorldTileState]
    objects: list[PlayerObject]
    objects_removed: list[str]
    connectors: list[WorldConnectorState]


class ContentResponse(TypedDict):
    kind: NotRequired[Literal['content']]
    revision: str
    descriptors: list[ContentDescriptor]


class ConditionFact(TypedDict):
    event_uuid: str | None
    condition_uuid: str
    name: str
    category: ConditionCategory
    behavior_id: str | None
    resulting_max_hp: int | None
    resulting_ac: int | None
    state: NotRequired[ConditionState | None]
    resulting_stats: NotRequired[EntityStatsState | None]
    resulting_tile: NotRequired[WorldTileState | None]
    resulting_item: NotRequired[ItemPresentationState | None]
    consumed: NotRequired[bool]


class EquipmentFact(TypedDict):
    kind: NotRequired[Literal['equipment']]
    source_entity_uuid: str
    visual_loadout: VisualLoadout
    armor_class: int
    controlled_items: NotRequired[list[ItemPresentationState] | None]


class PlayerActor(TypedDict):
    uuid: str
    name: str
    character_body_id: str | None
    creature_content_ref: str | None
    appearance: AppearanceConfig
    visual_loadout: VisualLoadout
    normal_hp: int
    maximum_hp: int
    temporary_hp: int
    life_state: LifeState
    armor_class: int
    conditions: NotRequired[list[ConditionFact]]
    last_visual_position: NotRequired[list[LastVisualPositionItem] | None]
    controlled_items: NotRequired[list[ItemPresentationState] | None]
    occupancy_layer: NotRequired[OccupancyLayer | None]
    temporary_hp_grant: NotRequired[TemporaryHitPointsGrant | None]
    resolved_size: NotRequired[Size | None]
    structural_base_size: NotRequired[Size | None]
    manifestation: NotRequired[SummonManifestation | None]
    faction: NotRequired[str | None]
    present: NotRequired[bool]
    remains_disposition: NotRequired[RemainsDisposition]
    spatial_disposition: NotRequired[SpatialDisposition]


class PlayerObservation(TypedDict):
    event_uuid: str
    actor: PlayerActor
    contact: PerceivedContact | None


class ConditionChangeFact(TypedDict):
    kind: NotRequired[Literal['condition']]
    target_entity_uuid: str
    event_type: EventType
    condition: ConditionFact
    consumed: NotRequired[bool]


class PlayerNode(TypedDict):
    uuid: str
    lineage_uuid: str
    parent_event: str | None
    parent_lineage: str | None
    children_lineages: list[str]
    phase: EventPhase
    canceled: bool
    fact: (
        AttackFact
        | SpellFact
        | AreaReachFact
        | MovementFact
        | StepFact
        | ForcedMovementFact
        | PortalTransferFact
        | ShoveFact
        | DamageRequestFact
        | DamageResultFact
        | HealFact
        | TemporaryHitPointsFact
        | LifeFact
        | DeathSaveFact
        | EquipmentFact
        | ConditionChangeFact
        | ItemEffectChangeFact
        | SpatialFact
        | FactionFact
        | TurnFact
        | ActionFact
        | SensoryFact
        | ItemChargeFact
        | SpatialEffectStateFact
        | ObjectDamageFact
        | ObjectDestroyedFact
        | MechanismActivationFact
        | SavingThrowFact
        | None
    )
    resolution_ref: NotRequired[EventResolutionRef | ApplicationResolutionRef | None]
    cancellation: NotRequired[ActionCancellation | None]
    combat_log: NotRequired[CombatLogEntry | None]
    turn_execution_id: NotRequired[str | None]
    content_attributions: NotRequired[list[ContentAttribution]]


class PlayerLineage(TypedDict):
    generation: str
    observer_uuid: str
    lineage_uuid: str
    root: PlayerNode | None
    events: list[PlayerNode]
    version_rows: list[VersionRow]
    start_cursor: int
    end_cursor: int
    observations: NotRequired[list[PlayerObservation]]
    world_updates: NotRequired[list[WorldUpdate]]
    hud_snapshot: NotRequired[PlayerHUDSnapshot | None]
    audience: NotRequired[PlayerAudience | None]


class PlayerOperation(TypedDict):
    audience: PlayerAudience
    lineages: list[PlayerLineage]
    hud: PlayerHUDSnapshot | None
    combat_log_appends: list[CombatLogAppend]
    content_additions: list[ContentDescriptor]
    kind: NotRequired[Literal['operation']]
    protocol: ProtocolIdentity
    cursor: PlayerCursor
    state_revision: str
    command_number: int | None
    boundary: BoundaryState


class PlayerInitialization(TypedDict):
    generation: str
    observer_uuid: str
    world: PlayerWorld
    nodes: list[PlayerNode]
    version_rows: list[VersionRow]
    end_cursor: int
    observations: list[PlayerObservation]
    world_updates: list[WorldUpdate]
    hud_snapshot: NotRequired[PlayerHUDSnapshot | None]
    audience: NotRequired[PlayerAudience | None]


class InitializationResponse(TypedDict):
    kind: NotRequired[Literal['initialization']]
    protocol: ProtocolIdentity
    cursor: PlayerCursor
    content_revision: str
    content_additions: list[ContentDescriptor]
    initialization: PlayerInitialization


type Model = HealthResponse | BootstrapResponse | StatusResponse | AttachmentRequest | AttachmentResponse | InitializationResponse | AckRequest | AckResponse | ChoicesRequest | ChoicesResponse | PreviewRequest | PreviewResponse | CommandRequest | ReceiptResponse | ContentResponse | StreamReady | StreamStatus | PlayerOperation | ApiError
